### ISSUE TITLE
Existing compressed file left untouched if Treshold is not met

### ISSUE THREAD

**Issue by alesvaupotic** [webpack-contrib/compression-webpack-plugin#104]
```
npm list | grep compression-webpack-plugin*
├─┬ compression-webpack-plugin@1.1.11
```

Example config:

```
mix.webpackConfig({
  plugins: [
    new CompressionPlugin({
      asset: "[path].gz[query]",
      algorithm: "gzip",
      test: /\.js$|\.css$|\.html$|\.svg$/,
      threshold: 10240,
      minRatio: 0.8
    })
  ],  
})
```

Now, if my `style.css` turns out to be 20Kb, it gets compressed to `style.css.gz`. After deleting most of my css and leaving file at 1Kb, compression doesn't run and `style.css.gz` is left untouched from previous run, serving the wrong content to the user.

Expected behaviour would be to delete the old .gz as the plugin is the "maintainer" of the file. It created it and should be responsible for disposal.

**Comment by evilebottnawi** [comment]
@alesvaupotic you don't delete `build/dist` directory?

**Comment by alesvaupotic** [comment]
@evilebottnawi No, never. I build directy to the public folder of a Laravel app and other stuff might live there which comes from others sources, so deleting it is not an option. I see it could work with some additional file juggling, sure. But as said before, if a module creates a file, it should also be responsible for taking it down if not needed anymore. It is simply a good practice.

**Comment by evilebottnawi** [comment]
@alesvaupotic you should remove *.gz files before every build, it is good practice :+1:

**Comment by evilebottnawi** [comment]
@alesvaupotic We try to keep the plugins as simple as possible. New options = new problems. We have other plugins and solution to remove files before build, better use their. Also we have `cache` option and you do not have to worry about performance.

**Comment by alesvaupotic** [comment]
Understood.
