### ISSUE TITLE
Unable to load gzipped version of import()ed assets

### ISSUE THREAD

**Issue by bawjensen** [webpack-contrib/compression-webpack-plugin#105]
I am working on a project at @thumbtack that gzips assets that internally use the ES6 dynamic `import()`. 

However, I cannot find a configuration of webpack/this specific plugin that allows me to load the dynamically generated assets as their gzipped version. If I specify the webpack `output.filename` field as `[name].js.gz` (which feels a bit like a hack), then I have to specify `asset: '[path][query]'` in this plugin's config and - more importantly - the files are no longer properly minified by webpack.

Frankly I couldn't quite figure out if this issue belongs here or in [webpack proper](https://github.com/webpack/webpack/). It seems to live somewhere in the middle.

### Minimal repo

https://github.com/bawjensen/webpack-gzip-import-issue

**Comment by evilebottnawi** [comment]
@bawjensen thanks for issue, need fix `test` options like here https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/master/src/index.js#L25

**Comment by evilebottnawi** [comment]
But looks changing test it is breaking change :disappointed:

**Comment by bawjensen** [comment]
oh, awesome, thanks @evilebottnawi. For some reason I was trying to find that `test` regex in webpack itself.

If we added a feature to `uglifyjs-webpack-plugin` to allow overriding of that `test` regex, would that be a breaking change?

**Comment by evilebottnawi** [comment]
@bawjensen we should do this in next major, we already support `test` here, but not it is `.` (i.e. any files), if we change this, it can breaking build for somebody

**Comment by bawjensen** [comment]
Ah, I misread, yeah. Sounds good, thanks :)

**Comment by bawjensen** [comment]
From testing with my own setup, making the test regex `.*` didn't work because then it attempted to minify some CSS in our build. So the test pattern I'm using now is `/\.js(\.gz)?$/` (or, to be consistent with the existing default `test`, it would be `/\.js(\.gz)?(\?.*)?$/`).

Not sure if this is still a breaking change, or perhaps too specific to this scenario of appending `.gz` to a filename.

**Comment by evilebottnawi** [comment]
@bawjensen you should compress not only `js`, not only `js`, because many web servers (include `nginx`) support `.gz` (for `nginx` you should enable module) for all assets

**Comment by bawjensen** [comment]
Right we're gzipping all assets, CSS included. The `test` I'm referring to above is the pattern that `uglifyjs-webpack-plugin` uses to determine which assets to minify.

**Comment by jfrux** [comment]
Same issue... I think?  After the assets are built, my dynamic imports are pulling the `.js` in browser versus the `.gz`... no option to like... rename the gz file back to its original after the conversion...?

**Comment by jfrux** [comment]
WHO POSTED THIS… IMPOSTER!
/cry

**Comment by jfrux** [comment]
Sorry, it does... not sure why I posted this.

**Comment by jfrux** [comment]
Actually, sorry but I'm using S3 static files host and I'm needing to change the filenames back to .js from .gz so I don't need an HTTP server to do that logic.

**Comment by evilebottnawi** [comment]
@jfrux why? i can't understand you
