### ISSUE TITLE
Integration into html-webpack-plugin

### ISSUE THREAD

**Issue by jairusd** [webpack-contrib/compression-webpack-plugin#106]
Hi, great work on this plugin guys, this isn't a bug report but a question. How do we use html webpack plugin with compression webpack plugin?

https://github.com/jantimon/html-webpack-plugin
https://github.com/jantimon/html-webpack-plugin/issues/1000

Thanks for the response!

**Comment by evilebottnawi** [comment]
@jairusd just use plugin, do you have problem or error or something doesn't work? Also please use `gitter`, `slack` or `stackoverflow` for question.

**Comment by jairusd** [comment]
Got it. I'll be closing this issue.

**Comment by nerdmax** [comment]
Just in case some one else find this issue later.

If you are using `html-webpack-plugin` along side `compression-webpack-plugin` and you want the `html-webpack-plugin` to reference the .gz file automatically.

You can try this plugin: [html-webpack-change-assets-extension-plugin](https://github.com/nerdmax/html-webpack-change-assets-extension-plugin).

Eg:
```javascript
plugins: [
  new HtmlWebpackPlugin({
    jsExtension: ".gz"
  }),
  new CompressionPlugin(), // compression plugin will generate the xxx.js.gz file
  new HtmlWebpackChangeAssetsExtensionPlugin()
];
```
