### ISSUE TITLE
Feature request: keep original asset but empty content

### ISSUE THREAD

**Issue by TheHolyWaffle** [webpack-contrib/compression-webpack-plugin#107]
Feature request:

New option: emptyOriginalAssets (boolean)

When emptyOriginalAssets is true then it will keep the original asset but makes sure that the content is empty. This is needed for certain webservers that rely on the original asset still being there when falling back from .gz file.

By emptying the original assets we can save some disk space.

**Comment by evilebottnawi** [comment]
@TheHolyWaffle please describe use case, if `gz` doesn't exists webserver try to get original (it is default behaviour)

**Comment by TheHolyWaffle** [comment]
My use case is sourcemaps. By compressing them I can save some disk space
when hosting them. But I still need the original files because that's how
they are referenced from the .js files. And not with their .gz variant. As
such, for example tomcat will see the http request to the .map file but it
will automatically redirect it to the .map.gz variant. This will not work
if the original .map file is removed, the http request will fail. Thats why
I need functionality to empty the original asset.

Op 28 aug. 2018 14:11 schreef "Evilebot Tnawi" <notifications@github.com>:

@TheHolyWaffle <https://github.com/TheHolyWaffle> please describe use case,
if gz doesn't exists webserver try to get original (it is default behaviour)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/webpack-contrib/compression-webpack-plugin/issues/107#issuecomment-416560807>,
or mute the thread

**Comment by evilebottnawi** [comment]
Sorry, it is out of scope this plugin, you can create own plugin for this rare use case.
