### ISSUE TITLE
Configure gzip compression level

### ISSUE THREAD

**Issue by rightaway** [webpack-contrib/compression-webpack-plugin#110]
Would be nice to have a feature to configure the gzip compression level that is used.

Which compression level is used by default? Should be added to documentation.

**Comment by evilebottnawi** [comment]
Done in https://github.com/webpack-contrib/compression-webpack-plugin/releases/tag/v2.0.0

Look here https://github.com/webpack-contrib/compression-webpack-plugin#compressionoptions
