### ISSUE TITLE
Does not work for chunks with 'special names'

### ISSUE THREAD

**Issue by SergeyShablenko** [webpack-contrib/compression-webpack-plugin#114]
* Operating System: Ubuntu 18
* Node Version: 10.10
* NPM Version: 6.4.1
* webpack Version: 4.17.1
* webpack-defaults Version: -

### Expected Behavior

Compress all assets

### Actual Behavior

does not work with chunks which names are like './some-path/'
chunks are created by webpack, and they are in separate folder as expected, but no gz files for those special chunks appeared neither in that separate folder nor in 'publicPath' folder 

### Code

```js
{
output: {
    path: CONFIG.dest,
    filename: '[chunkhash].js',
    chunkFilename: '[name][chunkhash].js',
    publicPath: CONFIG.publicPath
  },

optimization: {
splitChunks: {
      chunks: 'all',
      cacheGroups: {
        default: false,
        customChunk: {
          name: `./some-path/`,
          chunks: 'all',
          test: /[\\/]some-certain-folder\/sub-folder[\\/]/,
          enforce: true
        }
      }
    },
},

plugins: [
    new CompressionPlugin({
      asset: '[path].gz',
      algorithm: 'gzip',
      threshold: 10240,
      minRatio: 0.8
    })
]
}
```

**Comment by evilebottnawi** [comment]
@SergeyShablenko you should use ` test: /\.js(\?.*)?$/i` or what you need

**Comment by SergeyShablenko** [comment]
I don`t want to use anything, just gzip all assets and put them near their originals

**Comment by evilebottnawi** [comment]
@SergeyShablenko try to write `test: /\.*(\?.*)?$/i`

**Comment by SergeyShablenko** [comment]
Did not work

![selection_010](https://user-images.githubusercontent.com/13334277/46675576-65c39300-cbe7-11e8-825a-b2473fbdbcea.png)

**Comment by SergeyShablenko** [comment]
https://github.com/SergeyShablenko/test-compression-plugin
