### ISSUE TITLE
Cannot read property 'emit' of undefined

### ISSUE THREAD

**Issue by Yangfan2016** [webpack-contrib/compression-webpack-plugin#115]
* Operating System: linux x64
* Node Version: 10.6.0
* NPM Version: 6.1.0 
* webpack Version: 3.8.1
* webpack-defaults Version:

### Code

```js
new CompressionPlugin({
      filename: "[path].gz[query]",
      algorithm: "gzip",
      test: /\.(js|css|html)$/,
      threshold: 10240,
      minRatio: 0.8
    }),
```

**Comment by evilebottnawi** [comment]
@Yangfan2016 latest version require `webpack4`, please update `webpack` version or use `compression-webpack-plugin` version `1.x`

**Comment by Yangfan2016** [comment]
Thx

**Comment by sunnytambi** [comment]
downgraded to compression-webpack-plugin v1.1.12 and had everything working
