### ISSUE TITLE
No error is thrown when file is not generated due to minRatio check

### ISSUE THREAD

**Issue by chestozo** [webpack-contrib/compression-webpack-plugin#116]
Currently if the ratio of generated file size compared to original file size is greater than `options.minRatio` - compressed file is not being generated and no error is thrown.

Here is the check 
```js
if (result.length / originalSize > minRatio) {
  return cb();
}
```
https://github.com/webpack-contrib/compression-webpack-plugin/blob/master/src/index.js#L138

### Expected Behavior / Situation
Error is thrown.

### Actual Behavior / Situation
webpack build finishes without any trace of file not being generated (no error, no message).

### Modification Proposal
Default behavior:
throw error `File not generated due to file size being too big`.

Add option to support current behavior. Not sure about the name for example `option.dropBigFiles`.

**Comment by evilebottnawi** [comment]
It is expected behavior and no errors should be generated. You can use `minRatio` to compress all assets. Also you can use `test`/`include`/`exclude` option to filter files.
