### ISSUE TITLE
Brotli support

### ISSUE THREAD

**Issue by emilbader** [webpack-contrib/compression-webpack-plugin#118]
* Operating System: macOS Mojave (10.14.3)
* Node Version: 10.15.2
* NPM Version: 6.4.1
* webpack Version: 4.28.4
* webpack-defaults Version: N/A

### Feature Proposal
Node 11.7.0 has [native support](https://nodejs.org/api/zlib.html#zlib_zlib_createbrotlicompress_options) for Brotli compression in its `zlib` module.

### Feature Use Case
- Smaller files compared to Gzip:
    - ![image](https://user-images.githubusercontent.com/27896589/53734645-e16af880-3e84-11e9-90f3-fdf9a479a54f.png) **credit:** https://blog.kowalczyk.info/article/c11d3c20753445618b98d18be5ce037e/zopfli-vs.-brotli-vs.-gzip.html

- Not having to rely on external libraries like [iltorb](https://github.com/MayhemYDG/iltorb) used in [brotli-webpack-plugin](https://github.com/mynameiswhm/brotli-webpack-plugin)

**Comment by evilebottnawi** [comment]
Feel free to send a PR

**Comment by khalwat** [comment]
I'm happy to report that this already "just works" ->

```JavaScript
new CompressionPlugin({
        filename: '[path].br[query]',
        algorithm: 'brotliCompress',
        test: /\.(js|css|html|svg)$/,
        compressionOptions: { level: 9 },
        threshold: 10240,
        minRatio: 0.8,
        deleteOriginalAssets: false
    }),
new CompressionPlugin({
        filename: '[path].gz[query]',
        algorithm: 'gzip',
        test: /\.(js|css|html|svg)$/,
        compressionOptions: { level: 9 },
        threshold: 10240,
        minRatio: 0.8,
        deleteOriginalAssets: false
    }),
```

output:

```
-rw-rw-r--   1 andrew  staff    61K Mar  9 10:37 vendors~amplitudeplayer.161a2c2f6376e617a7f5.js
-rw-rw-r--   1 andrew  staff   9.0K Mar  9 10:37 vendors~amplitudeplayer.161a2c2f6376e617a7f5.js.br
-rw-rw-r--   1 andrew  staff    10K Mar  9 10:42 vendors~amplitudeplayer.161a2c2f6376e617a7f5.js.gz
-rw-rw-r--   1 andrew  staff    14K Mar  9 10:37 vendors~vuetable.64419ea49293de11cc61.js
-rw-rw-r--   1 andrew  staff   4.5K Mar  9 10:37 vendors~vuetable.64419ea49293de11cc61.js.br
-rw-rw-r--   1 andrew  staff   5.1K Mar  9 10:42 vendors~vuetable.64419ea49293de11cc61.js.gz
-rw-rw-r--   1 andrew  staff    96K Mar  9 10:37 vendors~vue~vueclickaway.6fb24bd01d62bc0ff86c.js
-rw-rw-r--   1 andrew  staff    31K Mar  9 10:37 vendors~vue~vueclickaway.6fb24bd01d62bc0ff86c.js.br
-rw-rw-r--   1 andrew  staff    35K Mar  9 10:42 vendors~vue~vueclickaway.6fb24bd01d62bc0ff86c.js.gz
```

**Comment by evilebottnawi** [comment]
@khalwat can you send a PR to `Example` section? Thanks!

**Comment by khalwat** [comment]
@evilebottnawi done -> https://github.com/webpack-contrib/compression-webpack-plugin/pull/119

**Comment by ahmad2smile** [comment]
Any way to support with `npm install brotli` for use case when we can't upgrade node version even in build system. I'm on node:8-jessie

**Comment by Sheffchenk0** [comment]
> I'm happy to report that this already "just works" (no need for a PR). You just need to be running Node 11.7.0 or later:
> 
> ```js
> new CompressionPlugin({
>         filename: '[path].br[query]',
>         algorithm: 'brotliCompress',
>         test: /\.(js|css|html|svg)$/,
>         compressionOptions: { level: 11 },
>         threshold: 10240,
>         minRatio: 0.8,
>         deleteOriginalAssets: false
>     }),
> new CompressionPlugin({
>         filename: '[path].gz[query]',
>         algorithm: 'gzip',
>         test: /\.(js|css|html|svg)$/,
>         compressionOptions: { level: 9 },
>         threshold: 10240,
>         minRatio: 0.8,
>         deleteOriginalAssets: false
>     }),
> ```
> 
> output:
> 
> ```
> -rw-rw-r--   1 andrew  staff    61K Mar  9 10:37 vendors~amplitudeplayer.161a2c2f6376e617a7f5.js
> -rw-rw-r--   1 andrew  staff   9.0K Mar  9 10:37 vendors~amplitudeplayer.161a2c2f6376e617a7f5.js.br
> -rw-rw-r--   1 andrew  staff    10K Mar  9 10:42 vendors~amplitudeplayer.161a2c2f6376e617a7f5.js.gz
> -rw-rw-r--   1 andrew  staff    14K Mar  9 10:37 vendors~vuetable.64419ea49293de11cc61.js
> -rw-rw-r--   1 andrew  staff   4.5K Mar  9 10:37 vendors~vuetable.64419ea49293de11cc61.js.br
> -rw-rw-r--   1 andrew  staff   5.1K Mar  9 10:42 vendors~vuetable.64419ea49293de11cc61.js.gz
> -rw-rw-r--   1 andrew  staff    96K Mar  9 10:37 vendors~vue~vueclickaway.6fb24bd01d62bc0ff86c.js
> -rw-rw-r--   1 andrew  staff    31K Mar  9 10:37 vendors~vue~vueclickaway.6fb24bd01d62bc0ff86c.js.br
> -rw-rw-r--   1 andrew  staff    35K Mar  9 10:42 vendors~vue~vueclickaway.6fb24bd01d62bc0ff86c.js.gz
> ```
> 
> Additional options can be found here: https://github.com/nodejs/node/blob/master/doc/api/zlib.md#compressor-options

“level” does not affect the compression quality for brotli. Compressed file size remains equal for compression level 1 and 11.
