### ISSUE TITLE
Allow multiple file outputs one for each algorithm

### ISSUE THREAD

**Issue by crhistianramirez** [webpack-contrib/compression-webpack-plugin#127]
- Operating System: Windows / Mac / Linux
- Node Version: 8.9.0
- NPM Version: 6.9.0
- webpack Version: 4.3.0
- compression-webpack-plugin Version: 3.0.0

### Feature Proposal
Allow plugin to generate multiple file outputs for multiple algorithms. Maybe algorithms can take an optional array format to indicate more than one file (per algorithm) should be generated.

### Feature Use Case
Since this plugin now supports brotli algorithm it would be nice to be able to output both gzip *and* brotli so that my server can serve up the appropriate file to the client based on the accept headers.

**Comment by evilebottnawi** [comment]
PR welcome

**Comment by crhistianramirez** [comment]
Huh... just created two instances of the plugin and that seemed to do the trick. Maybe I could just create a PR to document that?

```
// outputs both brotli and gzip files
new CompressionPlugin({
  filename: '[path].gz[query]',
  algorithm: 'gzip',
  test: /\.js$|\.css$|\.html$/,
  threshold: 10240,
  minRatio: 0.8,
}),
new CompressionPlugin({
  filename: '[path].br[query]',
  algorithm: 'brotliCompress',
  test: /\.(js|css|html|svg)$/,
  compressionOptions: { level: 11 },
  threshold: 10240,
  minRatio: 0.8,
})
```

**Comment by evilebottnawi** [comment]
@crhistianramirez it is workaround, maybe it is good idea support `algorithm` as array for better DX

**Comment by evilebottnawi** [comment]
After investigate i found what using multiple instances is better then using array of `algorithm`s because each `algorithm` potential can have difference options and it is increase plugin configurations and logic in code, just put this example in docs

**Comment by CyberCookie** [comment]
I wouldn't close this issue since having one instance per one algorithm have it's drawback:
If i want to use more than one algorithm and use option "deleteOriginalAssets: true" (no matter which instance i set this option in) - as a result i will get only one compressed format instead of all i specified
