### ISSUE TITLE
minRatio = 1 verbiage is wrong

### ISSUE THREAD

**Issue by hecktarzuli** [webpack-contrib/compression-webpack-plugin#130]
Documentation Is:
- [ ] Missing
- [ ] Needed
- [ ] Confusing
- [x] Wrong

### Please Explain in Detail...

Currently documentation says if you set minRatio to 1, everything will be compressed. This actually isn't true. It still won't compress files that are LARGER than the original. 

### Your Proposal for Changes

Update verbiage to explain what value is needed to truly compress all files.

**Comment by evilebottnawi** [comment]
Feel free to send a fix to docs

**Comment by hecktarzuli** [comment]
https://github.com/webpack-contrib/compression-webpack-plugin/pull/141

**Comment by evilebottnawi** [comment]
Thanks!
