### ISSUE TITLE
cache does not work in watch mode

### ISSUE THREAD

**Issue by akosyakov** [webpack-contrib/compression-webpack-plugin#133]
We are using code splitting in dev (watch) mode in order to avoid redownloading everything on page refresh but only changed bundles. But compression plugin keeps generating new compressed artifacts even for not changed bundles. I've tried to enable caching and it did not have any effect.

**Comment by akosyakov** [comment]
I see that record is found in the cache, but a new file is still emitted. So Express.js treats as a new resource.

**Comment by evilebottnawi** [comment]
Please create minimum reproducible test repo?

**Comment by akosyakov** [comment]
@evilebottnawi Here you go: https://github.com/akosyakov/compression-webpack-with-watch

In order to reproduce:
- run `yarn` in order to install dependencies and start watching
- look at timestamps in lib folder for both bundles and gzipped archives
- wait sometime
- change client.js
- look at timestamps again, bundle.js is not changed, but gzipped is changed

Here is a Gitpod snapshot to reproduce:
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io#snapshot/4d3e37c3-a029-4ff7-bb9d-dba8af2a414a)

![compression](https://user-images.githubusercontent.com/3082655/65662401-afea9200-e04d-11e9-8b85-aaf21684d2d5.gif)

**Comment by akosyakov** [comment]
@evilebottnawi does it look like an issue? Are you opened to a PR? What would be the proper solution? Skip emitting a new file if an original asset timestamp did not change?

**Comment by evilebottnawi** [comment]
A lot of issues, you can debug it and send a PR, sorry

**Comment by ernestostifano** [comment]
For anyone getting here. A temporary solution, if writing a plugin is a possibility, is to collect and update effectively emitted assets paths on 'compiler.hooks.assetEmitted' hook and passing them to "compression-webpack-plugin" `exclude` option on each watch run. I'm currently doing that until this issue is fixed.

For additional information, please see [this comment](https://github.com/webpack-contrib/compression-webpack-plugin/pull/134#issuecomment-612596223) on relative PR.

**Comment by evilebottnawi** [comment]
There are several solution:
- Implement on webpack side new API `isAssetEmitted` and skip files which already exists
- Cache our compressed assets in memory between compilations, now the `cache` option only for filesystem cache (sounds like hacky)
- migrate on the `assetEmitted` hook (it can break assets manifest plugins)
- migrate on the `optimizeAssets` hook (ideally for webpack@6), the main problem - a lot of plugins uses `emit` hook for adding new assets, but it is wrong, on `emit` hook plugins should not adding new assets. I think we will throw a warning for webpack@5/webpack@6 if a plugin added assets into `emit` hook

**Comment by evilebottnawi** [comment]
I need a little discussion with @sokra about it, in the near future I will find a solution, sorry for delay
