### ISSUE TITLE
Laravel mix configuration example in doc ?

### ISSUE THREAD

**Issue by neoteknic** [webpack-contrib/compression-webpack-plugin#135]
Documentation Is:

- [x] Missing
- [x] Needed
- [x] Confusing
- [ ] Not Sure?

Compression plugin isn't working with laravel mix, at the end of webpack.mix.js I have :

   ```js
...
mix.scripts([
    'node_modules/popper.js/dist/umd/popper.min.js',
    'node_modules/bootstrap/dist/js/bootstrap.min.js',
    ...
],'public/js/admin-all.js');

const CompressionPlugin = require('compression-webpack-plugin');

mix.webpackConfig({
    plugins: [
        new CompressionPlugin({
            filename: '[path].br[query]',
            algorithm: 'brotliCompress',
            test: /\.(js|css|html|svg)$/,
            compressionOptions: { level: 11 },
            minRatio: 1,
            deleteOriginalAssets: false,
        }),
    ]
});
```

I try to add many config option, (  include: 'public/*', ...), no success, I have only one mix.js.br file generated in public/ but I dont know why and where is this file ?
I want to compress generated files in public/js and public/css , like admin-all.js

webpack.mix.js is in project root folder.

Can you help me and add a laravel example in the doc ?

**Comment by evilebottnawi** [comment]
Please send an example in laravel mix repo, we don't add examples for external boilerplate/tools
