### ISSUE TITLE
*.html files are not compressed when using with nuxt generate

### ISSUE THREAD

**Issue by mseele** [webpack-contrib/compression-webpack-plugin#142]
- Operating System: MacOS X 10.15.2
- Node Version: 13.5.0
- NPM Version: 6.13.4
- webpack Version: 4.41.4
- compression-webpack-plugin Version: 3.0.1

### Expected Behavior

*.html files should be compressed in nuxt generate process with compression-webpack-plugin

### Actual Behavior

No compressed version of the *.html files is generated when running "nuxt generate". Only *.js, *.css & *.svg files in folder _nuxt are compressed. Anything outside of folder _nuxt (this is where the html files are) is not compressed.

### Code

This is how my build section of the nuxt.config.js file looks like:

```js
import CompressionPlugin from 'compression-webpack-plugin'

export default {
// ...
  build: {
    plugins: [
      new CompressionPlugin({
        filename: '[path].gz[query]',
        algorithm: 'gzip',
        minRatio: 1,
        test: /\.(js|css|html|svg)$/
      }),
      new CompressionPlugin({
        filename: '[path].br[query]',
        algorithm: 'brotliCompress',
        test: /\.(js|css|html|svg)$/,
        minRatio: 1,
        compressionOptions: { level: 11 }
      })
    ]
  }
}
```

### How Do We Reproduce?

create a helloworld nuxtjs application via https://nuxtjs.org/guide/installation/#using-code-create-nuxt-app-code- , execute `npm install compression-webpack-plugin --save-dev` and add the above code into `nuxt.config.js`.
Then run `npm run generate` und look what has been created in the dist folder.

For us, everything except the *.html files has been compressed as *.gz & *.br archives.

**Comment by evilebottnawi** [comment]
Please open issue in nuxt

**Comment by evilebottnawi** [comment]
Also try to use `minRatio: Number.MAX_SAFE_INTEGER`, maybe files have more size after gzip

**Comment by mseele** [comment]
I've tried with `minRatio: Number.MAX_SAFE_INTEGER`, same result. No html file compression

**Comment by evilebottnawi** [comment]
As i said early please open issue in nuxt, we use default webpack API, maybe nuxt modify configuration  or do something other what block compress html

**Comment by evilebottnawi** [comment]
Feel free to feedback or open a new issue if you found what problem in the plugin
