### ISSUE TITLE
deleteOriginalAssets 

### ISSUE THREAD

**Issue by borodadada** [webpack-contrib/compression-webpack-plugin#149]
Hello, if i use 
```
deleteOriginalAssets = true
```
my site project send 404 error, this options work on client side? 
```
deleteOriginalAssets  = false
```
Image with result build
https://i.ibb.co/myrVyWL/Snipaste-2020-01-21-20-34-48.png
This is norm? Why initial = js, not gz ?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
