### ISSUE TITLE
`{file}` instead of `[file]`?

### ISSUE THREAD

**Issue by unindented** [webpack-contrib/compression-webpack-plugin#15]
@sokra, all your plugins and loaders use `[...]` for variable interpolation in strings... Why does this one use `{file}`?

**Comment by sokra** [comment]
it's old...

**Comment by unindented** [comment]
Not worth bumping the minor version and changing?

**Comment by michael-ciniawsky** [comment]
This seems to be resolved already, if I missed something please reopen
