### ISSUE TITLE
`TypeError: util.promisify is not a function`

### ISSUE THREAD

**Issue by Jamesking56** [webpack-contrib/compression-webpack-plugin#150]
- Operating System: Ubuntu 18.04 LTS
- Node Version: `v6.14.1`
- NPM Version: `v6.13.6`
- webpack Version: `4.41.5` (usage via Symfony Encore)
- compression-webpack-plugin Version: `3.1.0`

### Expected Behavior

Running `encore production` builds successfully.

### Actual Behavior

`encore production` fails with:

`TypeError: util.promisify is not a function`

### Code

Usage is with Symfony encore, so essentially its this:

```js
let CompressionPlugin = require('compression-webpack-plugin')

Encore
	.addPlugin(new CompressionPlugin())


... lots more stuff ...
```

Which matches your Readme.

### How Do We Reproduce?

Try following your Readme in Node `v6.14.1`, I believe this is a BC-break that has happened. This only started happening after I upgraded from `2.0.0`.

Your Readme states `This module requires a minimum of Node v6.9.0 and Webpack v4.0.0.` which I am still meeting.

**Comment by evilebottnawi** [comment]
We don't support `node@6` https://github.com/webpack-contrib/compression-webpack-plugin/blob/master/package.json#L16, please update node version

**Comment by evilebottnawi** [comment]
We need fix the README file
