### ISSUE TITLE
Replace threshold value of 10240 with 1280

### ISSUE THREAD

**Issue by profy12** [webpack-contrib/compression-webpack-plugin#152]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

In documentation like in https://github.com/webpack-contrib/compression-webpack-plugin#using-brotli you are using a threshold value of 10240 bytes, but default MTU is 1280 bytes so it should be better to use 1280. 10240 is a correct value if bit, not with bytes.

### Your Proposal for Changes

Using threshold value of 1280 instead of 10240 in documentation.

**Comment by evilebottnawi** [comment]
Feel free to send a PR

**Comment by evilebottnawi** [comment]
After reading deep about MTU, I found `1280` is not default value, it depends on other things https://en.wikipedia.org/wiki/Maximum_transmission_unit, because it is just an example I want to keep it as is, anyway thanks for the issue and the PR, sorry
