### ISSUE TITLE
Minimum Node version is incorrect (in practice)

### ISSUE THREAD

**Issue by charliematters** [webpack-contrib/compression-webpack-plugin#165]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
We're currently on Node 10.15 (for no particular reason), and it appears that I could upgrade the plugin. However...

CHANGELOG.md says:
> minimum supported Node.js version is 10.13

yarn says:
> error move-file@2.0.0: The engine "node" is incompatible with this module. Expected version ">=10.17". Got "10.15.3"

### Your Proposal for Changes
Update the node version so that it is the minimum of all dependencies

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/npm/cacache/issues/37
