### ISSUE TITLE
Wrong node version requirement in Changelog

### ISSUE THREAD

**Issue by TobyPalmer** [webpack-contrib/compression-webpack-plugin#166]
Documentation Is:

- [x] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
Hi!
The changelog for verion 4.0.0 is saying that minimum required node version is 10.13 but is actually 10.17.

This is because of:
The dependency cacache is set to `^15.0.3` https://github.com/webpack-contrib/compression-webpack-plugin/blob/master/package.json#L44

And `cacache 15.0.3` is using `move-file 2.0.0` https://github.com/npm/cacache/blob/latest/package.json#L71

And `move-file 2.0.0` has a minimum required node version of 10.17 https://github.com/sindresorhus/move-file/blob/master/package.json#L14

### Your Proposal for Changes
My proposal is either to change the changelog to say minimum required node version is 10.17 or downgrade cacache so it matches the 4.0.0 changelog requirements says.

**Comment by evilebottnawi** [comment]
Problem on `cacache` side https://github.com/npm/cacache/issues/37, we can't fix it on our side, sorry

**Comment by evilebottnawi** [comment]
npm team ignore my issue, they like to do that
