### ISSUE TITLE
It does not compress files that are 0 kb in size.

### ISSUE THREAD

**Issue by isikhi** [webpack-contrib/compression-webpack-plugin#167]
- Operating System: Linux
- Node Version: 10.16
- NPM Version: 6.x
- webpack Version: 4.16.5
- compression-webpack-plugin Version: 3.1.0

### Expected Behavior

I was expecting it to compress all the files. Even they size 0.
I use optimized-css-assets-webpack-plugin for cleaning duplicated css. And as a result some files can output 0kb. But webpack compression plugin wont include these files in to gz

### Actual Behavior

It compresses files that are larger than 0 byte, that is.

### Code

```js
  const CompressionWebpackPlugin = require('compression-webpack-plugin')
  webpackConfig.plugins.push(
    new CompressionWebpackPlugin({
      filename: '[path].gz[query]',
      algorithm: 'gzip',
      test: new RegExp(
        '\.(' + config.build.productionGzipExtensions.join('|') + ')$'
      ),
      threshold: 0,
      minRatio: Number.MAX_SAFE_INTEGER
    })
  )
```

**Comment by evilebottnawi** [comment]
Yep, bug, feel free to send a PR

**Comment by isikhi** [comment]
@evilebottnawi I will take a glance next weekend.

**Comment by evilebottnawi** [comment]
Found it is not bug, just bad documentation, instead `Number.MAX_SAFE_INTEGER` you should use `Infinity`

**Comment by evilebottnawi** [comment]
Any number always are less then `Infinity` and `Infinity` is less then `Infinity`, so all assets will be compressed
