### ISSUE TITLE
deleteOriginalAssets - production build not working with it enabled

### ISSUE THREAD

**Issue by funder7** [webpack-contrib/compression-webpack-plugin#168]
Documentation Is:

- [ ] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
I've found the option "deleteOriginalAssets", after enabling it my production build was not working. I'm a bit confused, I saw the content encoded with gzip, so I thought that original assets were not needed to make the application work and enabled that option. 

In fact when the build was complete, the bundle analyzer shown a strange ouput (only one bundle).

I'm doing something wrong here, or maybe I'm not using this feature for its original purpose?  

### Your Proposal for Changes
Just add two lines into the documentation to explain when this option must be enabled.

Thanks! :-)

**Comment by evilebottnawi** [comment]
@funder7 

> I'm doing something wrong here, or maybe I'm not using this feature for its original purpose?

You need setup your server to serve gzip files, I can say how, because I don't know your server. 

You don't provide enough information what do you want achieve and what means "production build not working with it enabled", sorry I can help, anyway feel free to feedback

**Comment by funder7** [comment]
Hi, 
I've opened this issue because I thought having more information in the docs, regarding this topic would be a good idea .

I'm using Apache to serve the application, actually I don't have any configuration in my htaccess file, and here's why:

![immagine](https://user-images.githubusercontent.com/12503478/87420445-93681800-c5d5-11ea-944f-b78525696e54.png)

This is the response I'm getting from the server, as you can see the response enconding is `gzip`. 
I'm a bit confused, everything seems to be working, but if I keep only the gzipped resources and not the uncompressed, I receive a 404. 

What is misleading is the fact that the response is gzip encoded, so it's natural to think that webpack takes care of the redirection on your behalf without any server configuration.

Where i can get all the informations about this topic and how to configure webpack & the server? 

Thank you

**Comment by evilebottnawi** [comment]
I think th best place for this is stackoverflow, also there are a lot of articles hot to setup this, sorry configurations of servers out of our scope

**Comment by funder7** [comment]
![immagine](https://user-images.githubusercontent.com/12503478/87431484-fca45700-c5e6-11ea-8c93-b42f4c447e78.png)

So what's this button for?

**Comment by evilebottnawi** [comment]
For documentation of the plugin, not the server configuration

**Comment by funder7** [comment]
Exactly: I'm pointing out a situation here, where you can think that compression is active, by looking at response headers, while it's not, and the only way to notice is to enable `deleteOriginalAssets`, otherwise you will never find out that not compressed assets are being served. 
Why not add two lines of explanation on what `deleteOriginalAssets` its for, and how to configure webpack correctly?

**Comment by evilebottnawi** [comment]
> Whether to delete the original assets or not.

What is not clear here? And how is webpack related to your server?

**Comment by funder7** [comment]
Keep it as you like it. bye

**Comment by evilebottnawi** [comment]
You can send a PR to docs if something is not clear for you, I just don't understand what do you want to document

**Comment by funder7** [comment]
Before sending a PR it's better to understand if it will be accepted, anyway I was trying to tell you that maybe, other people like me, could think that the whole set of options related to chunks compression is working, while in fact it's not!

If you look at the screenshot that I've posted some days ago, there the browser is telling that the asset received from the server is compressed. But it's really compressed or not? I cannot understand it. The content-encoding is `gzip`. Ok, so I supposed that my configuration was working as expected. Then i enabled this option (`deleteOriginalAssets`) and suddenly the resources were returning 404 now. 
Here's what I mean by telling you that the documentation can be a bit more specific on what's happening, probably it's not a 100% webpack related information, but it still saves to the user a lot of time saying something like:
"If you enable asset compression, by default your server will serve the compressed resource if present, and if not it will use the uncompressed one.  If you want there's the `deleteOriginalAssets` option that deletes the uncompressed chunks once they are bundled. <em>"Warning: your server by default expects both files to present, if you want to keep only the compressed files, then you need to change the server configuration in order to server compressed resources directly, skipping the uncompressed file lookup, otherwise a 404 error will be returned"</em>.

I don't know if what's written here is right, I'm guessing how the server is doing the compressed files lookup. I don't know if all the servers behave the same, or each one has a different lookup strategy. 

The point is that until you set `deleteOriginalAssets` to true, you will not discovery that served resources are not compressed, while you think they are.

**Comment by evilebottnawi** [comment]
> "Warning: your server by default expects both files to present, if you want to keep only the compressed files, then you need to change the server configuration in order to serve compressed resources directly, skipping the uncompressed file lookup, otherwise a 404 error will be returned".

And yes and no, some servers can serve `gzip` files if they exists, some of them can't work `gzip`, amazon for example only works with `gzip`, also come of them supports `brotli`, some not. It is real very spefific and require the knowledge about your server

**Comment by funder7** [comment]
Ok, I see your point. 
In fact I still don't understand what happened in my case_ when I have both compressed and uncompressed assets on the server, the compressed asset is served (at least it seems like that), while if *only* the compressed is present, it returns 404. 

For me it's legit to think that the file resolution is managed by webpack, as it has this setting available. 
I assume that in this case the 404 is coming from the entry point not being found, while the other chunks are not affected by the deleteOriginalAssets setting: once the main bundle is found (compressed), then probably the 404 will not be thrown by the chunks: their reference is inside the main bundle. Correct?

**Comment by evilebottnawi** [comment]
I do not understand your problem, `deleteOriginalAssets` is remove original assets and keep only `gz` assets, it is useful for amazon and azure services, do not use this option if you use simple servers

**Comment by funder7** [comment]
that's it!! the magic info came out ;)
