### ISSUE TITLE
In WebPack4 (at least) cache algorithm isn't considered in cache key.

### ISSUE THREAD

**Issue by willstott101** [webpack-contrib/compression-webpack-plugin#170]
- Operating System: Linux
- Node Version: v13.12.0
- NPM Version: 6.14.5
- webpack Version: 4.43.0
- compression-webpack-plugin Version: 4.0.0

### Expected Behavior
Changing `algorithm` option changes the algorithm used to compress the output file.

### Actual Behavior
Output file is from the cache, and compressed using brotli (the first algorithm I had used for the file).

### How Do We Reproduce?

Compiling with say... `'brotliCompress'` whilst forgetting to change the `filename` will cache the brotli result. Subsequently changing the algorithm to `'gzip'`, and leaving the filename with a `.gz` filename suffix, will not invalidate the cache and brotli compressed results are returned! There is then no way to get gzip results without purging the cache.

**Comment by willstott101** [comment]
compression-webpack-plugin@4.0.0
webpack@4.25.1

**Comment by evilebottnawi** [comment]
Sorry, I don't understand you and you ignore the issue template, please fix it and I will reopen issue.

We invalidate cache when you change algorithm, here - https://github.com/webpack-contrib/compression-webpack-plugin/blob/master/src/index.js#L148

**Comment by willstott101** [comment]
```
> const s = require("serialize-javascript");
> s(zlib.gzip)
'function asyncBufferWrapper(buffer, opts, callback) {\n' +
  "      if (typeof opts === 'function') {\n" +
  '        callback = opts;\n' +
  '        opts = {};\n' +
  '      }\n' +
  '      return zlibBuffer(new ctor(opts), buffer, callback);\n' +
  '    }'
> s(zlib.deflate)
'function asyncBufferWrapper(buffer, opts, callback) {\n' +
  "      if (typeof opts === 'function') {\n" +
  '        callback = opts;\n' +
  '        opts = {};\n' +
  '      }\n' +
  '      return zlibBuffer(new ctor(opts), buffer, callback);\n' +
  '    }'
> s(zlib.brotliCompress)
'function asyncBufferWrapper(buffer, opts, callback) {\n' +
  "      if (typeof opts === 'function') {\n" +
  '        callback = opts;\n' +
  '        opts = {};\n' +
  '      }\n' +
  '      return zlibBuffer(new ctor(opts), buffer, callback);\n' +
  '    }'

```

**Comment by evilebottnawi** [comment]
Oh, yep, let's fix it
