### ISSUE TITLE
Consequent builds with 5.0.1 and zopfli cause fail

### ISSUE THREAD

**Issue by vitoyucepi** [webpack-contrib/compression-webpack-plugin#189]
- Operating System: `archlinux`
- Node Version: `12.18.3`
- NPM Version: `6.14.7`
- webpack Version: `4.44.1`
- compression-webpack-plugin Version: `5.0.1`

### Summary
Regression since 5.0.0
I use compression plugin and zopfli like in https://webpack.js.org/plugins/compression-webpack-plugin/ 
In 5.0.1 I will receive the build error in consequent builds.
The quick fix for me is `yarn install --force`

### Expected Behavior

1. Build project with `webpack --mode production --progress`
1. Do something or don't
1. Rebuild project with `webpack --mode production --progress`
1. Success

### Actual Behavior

1. Build project with `webpack --mode production --progress`
1. Do something or don't
1. Rebuild project with `webpack --mode production --progress`
1. Error

#### Ok
```
# yarn build
yarn run v1.22.5
$ webpack --mode production --progress
Hash: a7f9a7d0256e51ffae5f
Version: webpack 4.44.1
Time: 171ms
Built at: 09/02/2020 1:40:24 AM
     Asset       Size  Chunks             Chunk Names
   test.js  931 bytes       0  [emitted]  main
test.js.gz  447 bytes          [emitted]  
Entrypoint main = test.js
[0] ./src/index.js 0 bytes {0} [built]
Done in 0.69s.
```
#### Error
```
# yarn build
yarn run v1.22.5
$ webpack --mode production --progress
95% emitting CompressionPluginTypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (buffer.js:331:9)
    at Webpack4Cache.get (/tmp/test/node_modules/compression-webpack-plugin/dist/Webpack4Cache.js:53:41)
    at async /tmp/test/node_modules/compression-webpack-plugin/dist/index.js:280:23
    at async Promise.all (index 0)
    at async compressionFn (/tmp/test/node_modules/compression-webpack-plugin/dist/index.js:321:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### How Do We Reproduce?

https://gitlab.com/vitoyucepi/compression-webpack-plugin-regression-5.0.1-zopfli
5.0.0(Ok) https://gitlab.com/vitoyucepi/compression-webpack-plugin-regression-5.0.1-zopfli/-/jobs/714802445
5.0.1(Error) https://gitlab.com/vitoyucepi/compression-webpack-plugin-regression-5.0.1-zopfli/-/jobs/714802443

**Up:**
```js
algorithm(input, compressionOptions, callback) {
  return gzip(input, compressionOptions, (err, buffer) => {
    callback(err, Buffer.from(buffer));
  });
},
```

**Comment by evilebottnawi** [comment]
WIP

**Comment by evilebottnawi** [comment]
Found a bug, `gzip` return `Uint8Array`, but should return `Buffer`, I will fix it
