### ISSUE TITLE
Fallback file path option

### ISSUE THREAD

**Issue by taxilian** [webpack-contrib/compression-webpack-plugin#193]
- Operating System: N/A
- Node Version: N/A
- NPM Version: N/A
- webpack Version: N/A
- compression-webpack-plugin Version: 5.0.2

### Feature Proposal

Add an option such as `defaultFile` which contains the path to a file which -- if provided -- will be served up if no existing file matches, instead of just falling through to the next middleware.

### Feature Use Case

The simplest case is a Vue app I'm working on which has multiple SPAs at e.g. `/users` -- say I have `/assets` for my static assets and I already have this plugin in use for that, but I also have a `users.html` page which should be served up for `/users/*` -- currently I'm just reading the file and sending it, like so:

```
function spaFallbackFile(file: string, dir: string) {
    return (req: express.Request, res: express.Response, next: express.NextFunction) => {
        if ((req.method === 'GET' || req.method === 'HEAD') && req.accepts('html')) {
            res.sendFile(file, { root: dir }, (err: any) => err &&
                next()
                );
        } else {
            next();
        }
    };
}
```

This works, but it means that the .html file in question won't be served up with the precompressed files even though webpack is generating them. With this feature I could change this:

```
router.use("/users", spaFallbackFile(target, "users.html"));
```

to this:

```
router.use("/users", expressStaticGzip("path/to/assets/", {enableBrotli: true, defaultFile: 'users.html'}));
```

It would also be useful for cases where you may want to put static assets inside the path to a single page app -- granted, not something I think should usually be done, but it may make sense in many cases.

I'm willing to do the implementation for this, but you may be able to do it in just a few minutes and if not I at least would like to know that the PR would be accepted before I take the time =] For now I'm just accepting that my root html files won't be pre-compressed, which isn't really that big of a deal -- but it seems like something which would be easy to solve.

**Comment by evilebottnawi** [comment]
Sorry, out of scope this plugin, you can use `copy-webpack-plugin` and copy `default` file
