### ISSUE TITLE
Outdated filename template strings in README.md

### ISSUE THREAD

**Issue by vitoyucepi** [webpack-contrib/compression-webpack-plugin#196]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?
- [x] Outdated

### Please Explain in Detail...

As of v6.0.0 `filename` template variables were refactored.
But `README.md` still has `[path]` instead of `[file]` or `[path][base]` or `[base]`.
I don't understand why do you use `[path][base].gz` instead of `[file].gz` as a default `filename` template.

Also https://webpack.js.org/plugins/compression-webpack-plugin/ still serves cached version.

### Your Proposal for Changes

1. Replace `[path]` with `[file]` in `README.md` on lines:
    - 261
    - 399
    - 426
    - 433

1. Maybe replace `[path][base]` with `[file]` in other cases.
1. Invalidate cache for https://webpack.js.org/plugins/compression-webpack-plugin/.
    I don't know if it really necessary.

**Comment by evilebottnawi** [comment]
`[file]` === `[path][base]`, so `[path][base].gz` === `[file].gz`, it can be changed without breaking change, but webpack uses small units, we can't use `[name][ext]` instead `[base]`, because `[ext]` can be empty and will be misleading in docs

**Comment by vitoyucepi** [comment]
Still not fixed.
> Type: String|Function Default: "[path][base].gz"

But in table on line 52 you use
> filename | {String\|Function} | [base].gz | The target asset filename.
> -- | -- | -- | --

Line 261
> ```js
> module.exports = {
>   plugins: [
>     new CompressionPlugin({
>       filename: '[path].gz',
>     }),
>   ],
> };
> ```

Other `[path]` are on lines:
- 399
- 426
- 433

**Comment by vitoyucepi** [comment]
Don't do pr because of table alignment
https://github.com/vitoyucepi/compression-webpack-plugin/commit/ccfe556db08bd124d88b4bac85f4684cf4dc2775

**Comment by evilebottnawi** [comment]
I don't understand you

**Comment by evilebottnawi** [comment]
Oh, I see, fixed https://github.com/webpack-contrib/compression-webpack-plugin/pull/197

**Comment by vitoyucepi** [comment]
https://github.com/webpack-contrib/compression-webpack-plugin/blame/master/README.md#L52
Replace `[base].gz` with `[path][base].gz`

**Comment by evilebottnawi** [comment]
Fixed
