### ISSUE TITLE
Zopfli support

### ISSUE THREAD

**Issue by ai** [webpack-contrib/compression-webpack-plugin#2]
Zopfli allows to compress files better, that common gzip

**Comment by stephanos** [comment]
@ai still interested?

**Comment by ai** [comment]
Nope, I moved to Gulp.

**Comment by FredericHeem** [comment]
The PR creates 2 issues:
* Even if *node-zopfli* is not used, end users need to install python and a C++ compiler which is really annoying especially on windows.
* Behind a corporate firewall and with github blocked, *node-zopfli* cannot be installed.
What's your opinion of creating a new webpack plugin that supports  *node-zopfli* and remove it from this package ?

**Comment by ShaneCourtrille** [comment]
Or the node-zopfli version dependency needs to be better maintained.  The compiled binaries that would allow usage without python/VC++ for node v4 are only available for node-zopfli 2.x as per [here](https://github.com/pierreinglebert/node-zopfli/issues/76)

**Comment by DNx5** [comment]
i have problem with node-zopfli in windows too, after downloading and installing gigs of visual studio/sdk and other things but still can't get it to work for days. in the end I just manually changed the version of node-zopfli inside `compression-webpack-plugin`'s package.json into 2.0.0 and then it works fine.

**Comment by generalov** [comment]
@DNx5 try to install VC++ and Python on Windows with https://www.npmjs.com/package/windows-build-tools (it takes about 5 minutes on my machine).

**Comment by FredericHeem** [comment]
Or add `optional=false` in your `.npmrc` to avoid installing unnecessary dependencies.

**Comment by michael-ciniawsky** [comment]
@FredericHeem @DNx5 @generalov @ShaneCourtrille If one of you guys still have issues regarding this plugin and windows useage please open a new issue 😛
