### ISSUE TITLE
bug with multiple instance of compression-webpack-plugin in webpack 5 and inner cache

### ISSUE THREAD

**Issue by artem-malko** [webpack-contrib/compression-webpack-plugin#202]
- Operating System: macOS Catalina 10.15.6
- Node Version: v14.1.0
- NPM Version: v6.14.4
- webpack Version: v5.0.0-beta.31
- compression-webpack-plugin Version: v6.0.1

### Expected Behavior

Multiple compression-webpack-plugin instances (with different algorithm) creates different files with inner cache system of webpack

### Actual Behavior

Multiple compression-webpack-plugin instances (with different algorithm) creates the same file with inner cache system of webpack

### How Do We Reproduce?

I've created a repo with reproduction https://github.com/artem-malko/compression-webpack-plugin-miltiple-compression-bug

**Comment by evilebottnawi** [comment]
WIP

**Comment by artem-malko** [comment]
Cool! Super fast fix)
