### ISSUE TITLE
Error: EISDIR: illegal operation on a directory (same config fails under 6.x, works under 5.x)

### ISSUE THREAD

**Issue by csvan** [webpack-contrib/compression-webpack-plugin#204]
- Operating System: OSX 
- Node Version: 14.11
- NPM Version: 6.18
- webpack Version:  4.42.2
- compression-webpack-plugin Version: 6.0.2

### Expected Behavior

Compression should work and output the result to the target directories.

### Actual Behavior

The config below worked fine under 5.x, but fails with the following error on 6.x. I have looked at the breaking changes and cannot see that we are falling under any of them.

```
Error: EISDIR: illegal operation on a directory, open '/path/to/project/build/core/br/'
```
### Code

```js
plugins: [
     new CompressionPlugin({
        filename: '/br/[path][query]',
        algorithm: 'brotliCompress',
        test: /.*/,
        compressionOptions: { level: 11 },
        threshold: -1,
        minRatio: Number.MAX_SAFE_INTEGER,
      }),

      new CompressionPlugin({
        filename: '/gzip/[path][query]',
        algorithm: 'gzip',
        test: /.*/,
        threshold: -1,
        minRatio: Number.MAX_SAFE_INTEGER,
      })
]
```

### How Do We Reproduce?

Add the above config to a webpack config of choice.

**Comment by evilebottnawi** [comment]
Do not use `/`, it is unsafe, you write files in the root of file system, and you don't have rights on this, it is part of breaking change for `v6`

**Comment by evilebottnawi** [comment]
Also you can should `[path]` and need to use `[path][base].[ext]`, it is also part of breaking change
