### ISSUE TITLE
Plugin changes sourceMappingURL in compressed assets

### ISSUE THREAD

**Issue by aradzie** [webpack-contrib/compression-webpack-plugin#207]
- Operating System: linux
- Node Version: v14.13.1
- NPM Version: 6.14.8
- webpack Version: 5.1.1
- compression-webpack-plugin Version: 6.0.3

### Expected Behavior

Content of the compressed assets is identical to the content of the original assets.

### Actual Behavior

Compressed assets are not identical to the original assets and have invalid `sourceMappingURL` which breaks debugging in browsers.

### How Do We Reproduce?

Steps to reproduce:

1. Configure the `filename` output option to use the `contenthash` placeholder.
2. Add plugin `CompressionPlugin` to the webpack configuration.
3. Build a bundle with webpack.
4. Observe that the original and the compressed assets are not identical! The compressed javascript bundle has a different `sourceMappingURL`.

To demonstrate the issue I created a repository https://github.com/aradzie/webpack-bug

Please checkout and build yourself to observe the bug.

**Comment by aradzie** [comment]
I took a brief look at the source code of the plugin and couldn't find anything related to sourceMappingURL, so this might be a webpack bug.

**Comment by evilebottnawi** [comment]
Yep, bug, workaround `{ optimization: { realContentHash: false } }`

**Comment by evilebottnawi** [comment]
Fix will be in near future

**Comment by evilebottnawi** [comment]
@aradzie https://github.com/webpack/webpack/pull/11721

**Comment by evilebottnawi** [comment]
Please try to use `5.1.3`

**Comment by evilebottnawi** [comment]
Feel free to feedback

**Comment by aradzie** [comment]
Yep, the latest webpack release 5.1.3 fixed the issue. Thanks for the quick response!
