### ISSUE TITLE
Accept function as value for test, include and exclude options

### ISSUE THREAD

**Issue by thasmo** [webpack-contrib/compression-webpack-plugin#208]
- Operating System: Windows 10
- Node Version: 12
- NPM Version: 6
- webpack Version: 5
- compression-webpack-plugin Version: 6

### Expected Behavior / Situation
`test`, `include`, `exclude` options should accept type `Function` as value.

### Actual Behavior / Situation
`test`, `include`, `exclude`  only accept `{String|RegExp|Array<String|RegExp>}`.

### Modification Proposal
Make `test`, `include`, `exclude` options work with functions too.

**Comment by thasmo** [comment]
I'd like to do something like this; simplified:

```js
import mime from 'mime-types';
import compressible from 'compressible';

const plugin = new CompressionPlugin({
    test: (path) => compressible(mime.lookup(path)),
});
```

**Comment by evilebottnawi** [comment]
Sorry, out of scope plugin, it is core feature, also it was discussed, supporting function will reduce performance, you can use Promise and collect necessary information

**Comment by evilebottnawi** [comment]
https://github.com/webpack-contrib/compression-webpack-plugin/blob/master/src/index.js#L144
