### ISSUE TITLE
Sourcemaps are not emitted when excluded with `deleteOriginalAssets` option

### ISSUE THREAD

**Issue by sibiraj-sr** [webpack-contrib/compression-webpack-plugin#215]
- Operating System: MacOs Catalina 
- Node Version: 14.15
- NPM Version: 6.14.8
- webpack Version: 5.4.0
- compression-webpack-plugin Version: 6.0.5

### Expected Behavior

Sourcemap should be emitted with `deleteOriginalAssets` when excluded from compression.

### Actual Behavior

When `deleteOriginalAssets` is enabled and map files are excluded from the compression. It is expected that `js` files are compressed with the same filename and map files are emitted as it is. but the map files are not emitted.

### Code

```js
// webpack.config.js
const CompressionPlugin = require('compression-webpack-plugin')
const FileManagerPlugin = require('filemanager-webpack-plugin')

module.exports = {
  mode: 'production',
  devtool: 'source-map',
  plugins: [
    new FileManagerPlugin({
      events: {
        onStart: {
          delete: ['dist/']
        }
      }
    }),
    new CompressionPlugin({
      filename: '[file]',
      exclude: /.map$/,
      minRatio: 10,
      deleteOriginalAssets: true
    })
  ]
}

```

### How Do We Reproduce?

Run webapck with the given config. the dist folder should have a compressed `main.js` and uncompressed `main.js.map`, but the map file is not emitted.

**Comment by evilebottnawi** [comment]
Expected, remove original source means remove source maps too

**Comment by sibiraj-sr** [comment]
Thanks @evilebottnawi . 

Anyway we could achieve this? I believe this is a general expectation. If this can't be fixed. Compression has to be done outside webpack I guess.

**Comment by sibiraj-sr** [comment]
I was just thinking `deleteOriginalAssets` should have been something like `overwriteOriginalAssets` 🤔 .

**Comment by evilebottnawi** [comment]
No new options, we can improve this, `deleteOriginalAssets: true | false | 'keep-source-map'`, but it will not easy to achieve

**Comment by sibiraj-sr** [comment]
Sounds good. I can give it a try. Can you put out a help wanted label. Incase you are busy. Someone can take this?

**Comment by evilebottnawi** [comment]
Yes, but nobody will take :smile: because it OSS

**Comment by sibiraj-sr** [comment]
A Sad truth. 😅

**Comment by evilebottnawi** [comment]
I think I was wrong here https://github.com/webpack-contrib/compression-webpack-plugin/blob/master/src/index.js#L303, it is easy:
```js
if (this.options.deleteOriginalAssets) {
  if (this.options.deleteOriginalAssets === 'keep-source-map) { 
     CompressionPlugin.updateAsset(
              compilation,
              name,
              inputSource,
              // Here we have link on source map file, we should just remove it from object and webpack keep source maps
              {}
    );

  }

  CompressionPlugin.deleteAsset(compilation, name);
}
```

**Comment by evilebottnawi** [comment]
You can try, it should be really easy

**Comment by sibiraj-sr** [comment]
Sure. Thanks for the tip.

**Comment by sibiraj-sr** [comment]
@evilebottnawi I tried. But the sourceMap property alone seems can't be removed. This is what I did.

```js
if (this.options.deleteOriginalAssets) {
  if (this.options.deleteOriginalAssets === "keep-source-map") {
    const { sourceMap, ...related } = info.related || {}; // <---- removing the property here

    const newAssetInfo = {
      ...info,
      related,
    };

    CompressionPlugin.updateAsset(compilation, name, inputSource, newAssetInfo);
  }

  const currentAsset = CompressionPlugin.getAsset(compilation, name);
  console.log(currentAsset.info); // <--- still has the sourceMap value inside related object

  CompressionPlugin.deleteAsset(compilation, name);
} else {
  // existing logic
}
```

**Comment by sibiraj-sr** [comment]
```js
const newAssetInfo = {
  ...info,
  related: { ...info.related, sourceMap: null },
};

CompressionPlugin.updateAsset(compilation, name, inputSource, newAssetInfo);
```

@evilebottnawi . removing the string doesn't work. some value has to be set for the  `sourceMap`. I am setting it to `null`. Is that fine?

**Comment by evilebottnawi** [comment]
Let's use `delete newAssetInfo.related.sourceMap`, you should do it before https://github.com/webpack-contrib/compression-webpack-plugin/blob/master/src/index.js#L303

**Comment by sibiraj-sr** [comment]
Actually thats what I did first.

```js
if (this.options.deleteOriginalAssets) {
  if (this.options.deleteOriginalAssets === "keep-source-map") {
    const { sourceMap, ...related } = info.related || {}; // <--- Removing the source map property.
    const newOriginalInfo = {
      ...info,
      related,
    };

    CompressionPlugin.updateAsset(
      compilation,
      name,
      inputSource,
      newOriginalInfo
    );

    console.log(newOriginalInfo);
  }

  const currentAsset = CompressionPlugin.getAsset(compilation, name);
  console.log(currentAsset.info); // <--- Still having source-map property in related info

  CompressionPlugin.deleteAsset(compilation, name);
} else {
  // existing logic
}
```

only setting a new value to it works. else the property is added back again.

**Comment by evilebottnawi** [comment]
Do it work?

**Comment by sibiraj-sr** [comment]
Setting it to null works. but I am just little not sure if it, whether it will create any unintended sideeffects?

**Comment by evilebottnawi** [comment]
No side effect, here simple logic, when something removed webpack automatically remove all related, so if you want keep something just remove it from `related`
