### ISSUE TITLE
Issue with compression of asset created during child compilation 

### ISSUE THREAD

**Issue by jeffposnick** [webpack-contrib/compression-webpack-plugin#218]
- Operating System: macOS 10.15.7
- Node Version: 12.18.3
- NPM Version: 6.14.6
- webpack Version: 5.4.0
- compression-webpack-plugin Version: 6.1.0

### Expected Behavior

When using `CompressionPlugin` alongside a plugin that performs a child compilation, like `workbox-webpack-plugin`'s `InjectManifest`, and compressing an asset created during that child compilation, the compression shouldn't happen until the appropriate stage in the main compilation.

### Actual Behavior

Because `CompressionPlugin` taps into `compilation`, rather than `thisCompilation`, it ends up running immediately following the child compilation orchestrated by `workbox-webpack-plugin`'s `InjectManifest` mode: The code in question is https://github.com/webpack-contrib/compression-webpack-plugin/blob/7eaf1ffce1e7a8a68444d3aa9fc529e89ae2e08f/src/index.js#L361

However, at that point, the asset created by `InjectManifest`'s child compilation isn't "finalized", and there is still some replacement that `InjectManifest` needs to perform as part of the main compilation ([here's the code that does that](https://github.com/GoogleChrome/workbox/blob/57ad215913b95f854f6ac981c77cb3536c46de48/packages/workbox-webpack-plugin/src/inject-manifest.js#L167-L177)). I see `CompressionPlugin` run a second time after `InjectManifest` has finished its replacement, but at that point, it doesn't look like it overwrites the previous compression that took place. (I think there's caching going on that prevents it from overwriting?)

I'm not an expert here compared to the maintainers, but I *think* that `CompressionPlugin` needs to either tap into `thisCompilation` (so that it's only run once, at the end of the main compilation), or alternatively, ensure that compression that's done during child compilation can be overwritten by a compression pass at the end of the main compilation.

### Code

```js
// webpack.config.js

{
  plugins: [
    new WorkboxPlugin.InjectManifest({
      swSrc: './src/sw.js',
      swDest: 'sw.js',
      exclude: [/\.(gz|br)$/],
    }),
    new CompressionPlugin({
      algorithm: 'gzip',
      minRatio: 0.8,
      test: /\.(js|css|html|svg)$/,
   })
  ]
}
```

### How Do We Reproduce?

Please see https://github.com/GoogleChrome/workbox/issues/2667

**Comment by evilebottnawi** [comment]
> When using CompressionPlugin alongside a plugin that performs a child compilation, like workbox-webpack-plugin's InjectManifest, and compressing an asset created during that child compilation, the compression shouldn't happen until the appropriate stage in the main compilation.

No, child compilations can create new assets and we should compress them, otherwise it will be bug and some plugins like svg generator will not work

**Comment by evilebottnawi** [comment]
You can prevent it by passing `compressed` (https://github.com/webpack-contrib/compression-webpack-plugin/blob/master/src/index.js#L185), but I found it hacky and weird

**Comment by evilebottnawi** [comment]
You have same problems with all minimizers by the way and many other plugins, we need fix it on `workbox-plugin-side`

**Comment by evilebottnawi** [comment]
You need delete assets from child compilation and re emit them again on the top compilation in your case, anyway I need to look at this deeply, will do tomorrow

**Comment by evilebottnawi** [comment]
Small example, not tested:
```js
 for(const asset of /* here child compilation */ compilation.getAssets()) {
        const buildInfo = this._module.buildInfo;
        
        if (!buildInfo.assets) {
          buildInfo.assets = Object.create(null);
        }
        
       if (!buildInfo.assetsInfo) {
          buildInfo.assetsInfo = new Map();
        }

        // For webpack@5 you need to use `emitAsset`
        buildInfo.assets[asset.name] = asset.source;
        buildInfo.assetsInfo.set(asset.name, asset.info);
      }
```

**Comment by evilebottnawi** [comment]
Or you can use `*` asset name like internal, but I found it also hacky

**Comment by jeffposnick** [comment]
Thanks for your help!

I am not sure at what point code similar to https://github.com/webpack-contrib/compression-webpack-plugin/issues/218#issuecomment-725571732 is meant to be run. [There's a block of code in my plugin](https://github.com/GoogleChrome/workbox/blob/57ad215913b95f854f6ac981c77cb3536c46de48/packages/workbox-webpack-plugin/src/inject-manifest.js#L215-L226), executed by tapping into the main compilation's `make` hook, that calls `childCompiler.runAsChild()` and then executes a callback. Is the code you provided meant to be run inside of that callback?

I don't see any code in your example that deletes the assets from the child compilation, just code that adds assets to `buildInfo` (which I assume is associated with the main compilation). Was that just an oversight?

Taking a step back, does every `webpack` plugin that creates during a child compilation have to explicitly delete those assets from the child compilation, and add them to the main compilation? If so... can that be something that `webpack` does automatically? There is little documentation out there around child compilation best practices, and this seems like something that many other plugins would get wrong as well.

**Comment by evilebottnawi** [comment]
> I don't see any code in your example that deletes the assets from the child compilation, just code that adds assets to buildInfo (which I assume is associated with the main compilation). Was that just an oversight?

And yes and no, based on your case, if you need only assets without related you need to delete them, if you need just add code, you can use updateAssets

> Taking a step back, does every webpack plugin that creates during a child compilation have to explicitly delete those assets from the child compilation, and add them to the main compilation? If so... can that be something that webpack does automatically? There is little documentation out there around child compilation best practices, and this seems like something that many other plugins would get wrong as well.

Here is not best way, it depends on what you need, I will look at the plugin code + adding test here to avoid future regressions + provide fix for your case

**Comment by evilebottnawi** [comment]
@jeffposnick plugin broken on windows:
```
FAIL test/CompressionPlugin.test.js
  ● Console

    console.log
      Current webpack version: 5

      at Object.<anonymous> (test/helpers/snapshotResolver.js:10:9)

    console.warn
      'D:acompression-webpack-plugincompression-webpack-plugin
      ode_modulesworkbox-precaching/precacheAndRoute.mjs' is imported by C:\Users\RUNNER~1\AppData\Local\Temp\761e4cac8006f7a9506aee8c05a29df6\service-worker.js, but could not be resolved – treating it as an external dependency

      at Object.defaultOnWarn [as onwarn] (node_modules/rollup/dist/shared/rollup.js:34:42)
      at ModuleLoader.handleResolveId (node_modules/rollup/dist/shared/rollup.js:18395:26)
      at node_modules/rollup/dist/shared/rollup.js:18362:22
          at async Promise.all (index 0)
      at ModuleLoader.fetchStaticDependencies (node_modules/rollup/dist/shared/rollup.js:18360:34)
          at async Promise.all (index 0)
      at ModuleLoader.fetchModule (node_modules/rollup/dist/shared/rollup.js:18337:9)
          at async Promise.all (index 0)
```

Why do you want to use rollup in build step, why do you prepare it before, it will reduce build time very well.

**Comment by evilebottnawi** [comment]
Also if you want to improve build time, pass `minimized: true` in assets info for minimized files

**Comment by evilebottnawi** [comment]
Fixed https://github.com/webpack-contrib/compression-webpack-plugin/releases/tag/v6.1.1, after discussion we decide run only minimizers on child compilation, because you and inject values from child compilations in source of assets

**Comment by jeffposnick** [comment]
> Fixed https://github.com/webpack-contrib/compression-webpack-plugin/releases/tag/v6.1.1, after discussion we decide run only minimizers on child compilation, because you and inject values from child compilations in source of assets

Thank you! So to be clear, the changes you suggested making in https://github.com/webpack-contrib/compression-webpack-plugin/issues/218#issuecomment-725570189 do not need to be implemented in `InjectManifest`?

> You have the same problems with all minimizers (double minification) by the way and many other plugins, we need fix it on workbox-plugin-side

So does the change you just made to `CompressionPlugin`, so that it taps into `thisCompilation`, also need to be made to other plugins? If someone complains in the Workbox issue tracker about an incompatibility with another plugin that needs to make the same change, should I just refer the plugin's author to this bug?

> Why do you want to use rollup in build step, why do you prepare it before, it will reduce build time very well.

`workbox-webpack-plugin` exports two plugins. `GenerateSW` is fundamentally different from `InjectManifest`. `GeneratewSW` creates a new service worker asset from scratch, and it relies on the same logic that `workbox-build`'s `generateSW` mode uses, which in turn uses Rollup for bundling. `InjectManifest` takes a user's handwritten service worker file, runs it through a `webpack` child compilation (not Rollup), and then injects the generated precache manifest.

**Comment by evilebottnawi** [comment]
> Thank you! So to be clear, the changes you suggested making in #218 (comment) do not need to be implemented in InjectManifest?

Yes

> So does the change you just made to CompressionPlugin, so that it taps into thisCompilation, also need to be made to other plugins?

No, depends on usage, but most of plugins already in right way

>If someone complains in the Workbox issue tracker about an incompatibility with another plugin that needs to make the same change, should I just refer the plugin's author to this bug?

Perhaps yes, but I don't think you will faced with it, edge case

> workbox-webpack-plugin exports two plugins. GenerateSW is fundamentally different from InjectManifest. GeneratewSW creates a new service worker asset from scratch, and it relies on the same logic that workbox-build's generateSW mode uses, which in turn uses Rollup for bundling. InjectManifest takes a user's handwritten service worker file, runs it through a webpack child compilation (not Rollup), and then injects the generated precache manifest.

But why you need rollup for this? I found it is some weirdly, webpack do it

**Comment by jeffposnick** [comment]
Thanks for clarifying all that!

> But why you need rollup for this? I found it is some weirdly, webpack do it

Developers use Workbox in a number of different ways, and a lack of consistency in how Workbox (in it's "generate a SW for me" mode) operates has historically been a source of bugs and developer confusion. Sharing as much code and configuration as possible between our `workbox-build`, `workbox-cli`, and `workbox-webpack-plugin` build tools is our solution, even if it means that, e.g., the `webpack` plugin ends up running code via external libraries that could be handled natively by `webapck`.

**Comment by evilebottnawi** [comment]
thanks for the answer, just don't forget to pass `minimized: true`, if you pass already uglified assets to reduce build time
