### ISSUE TITLE
GitHub is trying to autolink some numbers

### ISSUE THREAD

**Issue by jonnybarnes** [webpack-contrib/compression-webpack-plugin#221]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

Looking at the plugins for brotli compression here: https://webpack.js.org/plugins/compression-webpack-plugin/#using-brotli

The example is meant to set the `zlib.constants.BROTLI_PARAM_QUALITY` value to be `11`. When this has been processed by whatever workflow to get it ready for the site, that line has now become:

    [zlib.constants.BROTLI_PARAM_QUALITY]: https://github.com/webpack-contrib/compression-webpack-plugin/blob/master/11,

### Your Proposal for Changes

I’m not sure how you’re generating the HTML for webpack.js.org, but it shouldn’t be doing that

**Comment by evilebottnawi** [comment]
@webpack-bot move to webpack/webpack.js.org

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack/webpack.js.org/issues/4175, thanks for the issue
