### ISSUE TITLE
TypeError: Cannot read property 'tapPromise' of undefined for webpack 5.9.0

### ISSUE THREAD

**Issue by wangmeng1991** [webpack-contrib/compression-webpack-plugin#227]
- Operating System: macOS 11.0.1
- Node Version: v15.3.0
- NPM Version: 6.14.9
- webpack Version: 5.9.0
- compression-webpack-plugin Version: 7.0.0

### Expected Behavior

compressed files

### Actual Behavior
```
ERROR  TypeError: Cannot read property 'tapPromise' of undefined
TypeError: Cannot read property 'tapPromise' of undefined
    at /Users/lean/IdeaProjects1/dls-vue/node_modules/compression-webpack-plugin/dist/index.js:269:39
    at SyncHook.eval [as call] (eval at create (/Users/lean/IdeaProjects1/dls-vue/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:19:1)
    at SyncHook.lazyCompileHook (/Users/lean/IdeaProjects1/dls-vue/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/lean/IdeaProjects1/dls-vue/node_modules/webpack/lib/Compiler.js:631:26)
    at /Users/lean/IdeaProjects1/dls-vue/node_modules/webpack/lib/Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/lean/IdeaProjects1/dls-vue/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/lean/IdeaProjects1/dls-vue/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/Users/lean/IdeaProjects1/dls-vue/node_modules/webpack/lib/Compiler.js:662:28)
    at /Users/lean/IdeaProjects1/dls-vue/node_modules/webpack/lib/Compiler.js:321:11
    at Compiler.readRecords (/Users/lean/IdeaProjects1/dls-vue/node_modules/webpack/lib/Compiler.js:529:11)
    at /Users/lean/IdeaProjects1/dls-vue/node_modules/webpack/lib/Compiler.js:318:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/lean/IdeaProjects1/dls-vue/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/lean/IdeaProjects1/dls-vue/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/lean/IdeaProjects1/dls-vue/node_modules/webpack/lib/Compiler.js:315:19
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/lean/IdeaProjects1/dls-vue/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/lean/IdeaProjects1/dls-vue/node_modules/tapable/lib/Hook.js:154:20)
```

### Code
```js
// vue.config.js
module.exports = {
  configureWebpack: (config) => {
    const plugins = [];
    // gzip
    const CompressionWebpackPlugin = require("compression-webpack-plugin");
    const productionGzipExtensions = /\.(js|css|json|txt|html|ico|svg)(\?.*)?$/i;
    plugins.push(
      new CompressionWebpackPlugin({
        filename: "[path][base].gz[query]",
        algorithm: "gzip",
        test: productionGzipExtensions,
        threshold: 10240,
        minRatio: 0.8,
      })
    );

    config.plugins = [...config.plugins, ...plugins];
  },
};

```

### How Do We Reproduce?

npm run build

**Comment by imLiukai** [comment]
> * Operating System: macOS 11.0.1
> * Node Version: v15.3.0
> * NPM Version: 6.14.9
> * webpack Version: 5.9.0
> * compression-webpack-plugin Version: 7.0.0
> 
> ### Expected Behavior
> compressed files
> 
> ### Actual Behavior
> ```
> ERROR  TypeError: Cannot read property 'tapPromise' of undefined
> TypeError: Cannot read property 'tapPromise' of undefined
>     at /Users/lean/IdeaProjects1/dls-vue/node_modules/compression-webpack-plugin/dist/index.js:269:39
>     at SyncHook.eval [as call] (eval at create (/Users/lean/IdeaProjects1/dls-vue/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:19:1)
>     at SyncHook.lazyCompileHook (/Users/lean/IdeaProjects1/dls-vue/node_modules/tapable/lib/Hook.js:154:20)
>     at Compiler.newCompilation (/Users/lean/IdeaProjects1/dls-vue/node_modules/webpack/lib/Compiler.js:631:26)
>     at /Users/lean/IdeaProjects1/dls-vue/node_modules/webpack/lib/Compiler.js:667:29
>     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/lean/IdeaProjects1/dls-vue/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
>     at AsyncSeriesHook.lazyCompileHook (/Users/lean/IdeaProjects1/dls-vue/node_modules/tapable/lib/Hook.js:154:20)
>     at Compiler.compile (/Users/lean/IdeaProjects1/dls-vue/node_modules/webpack/lib/Compiler.js:662:28)
>     at /Users/lean/IdeaProjects1/dls-vue/node_modules/webpack/lib/Compiler.js:321:11
>     at Compiler.readRecords (/Users/lean/IdeaProjects1/dls-vue/node_modules/webpack/lib/Compiler.js:529:11)
>     at /Users/lean/IdeaProjects1/dls-vue/node_modules/webpack/lib/Compiler.js:318:10
>     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/lean/IdeaProjects1/dls-vue/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
>     at AsyncSeriesHook.lazyCompileHook (/Users/lean/IdeaProjects1/dls-vue/node_modules/tapable/lib/Hook.js:154:20)
>     at /Users/lean/IdeaProjects1/dls-vue/node_modules/webpack/lib/Compiler.js:315:19
>     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/lean/IdeaProjects1/dls-vue/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
>     at AsyncSeriesHook.lazyCompileHook (/Users/lean/IdeaProjects1/dls-vue/node_modules/tapable/lib/Hook.js:154:20)
> ```
> 
> ### Code
> ```js
> // vue.config.js
> module.exports = {
>   configureWebpack: (config) => {
>     const plugins = [];
>     // gzip
>     const CompressionWebpackPlugin = require("compression-webpack-plugin");
>     const productionGzipExtensions = /\.(js|css|json|txt|html|ico|svg)(\?.*)?$/i;
>     plugins.push(
>       new CompressionWebpackPlugin({
>         filename: "[path][base].gz[query]",
>         algorithm: "gzip",
>         test: productionGzipExtensions,
>         threshold: 10240,
>         minRatio: 0.8,
>       })
>     );
> 
>     config.plugins = [...config.plugins, ...plugins];
>   },
> };
> ```
> 
> ### How Do We Reproduce?
> npm run build

compression-webpack-plugin Version 6.0.0 work fine!

**Comment by imLiukai** [comment]
@wangmeng1991  compression-webpack-plugin Version 6.0.0 work fine!

**Comment by gee1k** [comment]
+1

**Comment by Ethan-yt** [comment]
+1

**Comment by alexander-akait** [comment]
You still use old version of webpack - i.e. v4
