### ISSUE TITLE
Compressed file is not emitted in webpack 5

### ISSUE THREAD

**Issue by jkevingutierrez** [webpack-contrib/compression-webpack-plugin#228]
- Operating System: macOS 10.15.7
- Node Version: 14.15.0
- NPM Version: 6.14.9
- webpack Version: 5.9.0
- compression-webpack-plugin Version: 7.0.0 wp

### Expected Behavior

The file generated by compression-webpack-plugin should be emitted

![image](https://user-images.githubusercontent.com/6220055/101099523-cade5d80-3592-11eb-9e72-8c11f04f13b2.png)

### Actual Behavior

The file generated by compression-webpack-plugin is not emitted in Webpack v5

![image](https://user-images.githubusercontent.com/6220055/101099492-bac67e00-3592-11eb-835d-518d22f76839.png)

### Code

```js
// webpack.config.js
const { CleanWebpackPlugin } = require('clean-webpack-plugin');
const Compression = require('compression-webpack-plugin');
const Path = require('path');
const { WebpackManifestPlugin } = require('webpack-manifest-plugin');

module.exports = {
	entry: {
    input: './input.js',
  },
  mode: 'development',
  output: {
    filename: '[name].js',
    path: Path.join(__dirname, 'dist'),
    publicPath: '',
  },
  plugins: [
    new CleanWebpackPlugin(),
    new Compression(),
    new WebpackManifestPlugin(),
  ],
};
```

### How Do We Reproduce?

https://repl.it/@jkevingutierrez/manifest-plugin-repro#webpack.config.js

It was working before in webpack v4: https://repl.it/@jkevingutierrez/manifest-plugin-repro-1#webpack.config.js

**Comment by alexander-akait** [comment]
Can't reproduce, all works fine:
```
[webpack-cli] Compilation finished
PublicPath: (none)
asset input.js 908 bytes {input} [emitted] (name: input)
  gzipped input.js.gz 501 bytes [emitted] [compressed]
asset manifest.json 28 bytes [emitted]
Entrypoint input 908 bytes = input.js
chunk {input} (runtime: input) input.js (input) 58 bytes [entry] [rendered]
  > ./input.js  input
./input.js 58 bytes {input} [depth 0] [built] [code generated]
  [used exports unknown]
```

Don't use `webpack-nano`, you don't need it, please use `webpack-cli` (official CLI for webpack)

In webpack@5 related assets are hidden from stats to reduce memory usage, you can use `--stats=detailed`
