### ISSUE TITLE
Cannot read property 'tapPromise' of undefined

### ISSUE THREAD

**Issue by afzaalahmad** [webpack-contrib/compression-webpack-plugin#229]
- Operating System: Ubuntu 20.04
- Node Version: v12.20.0
- Yarn Version: v1.22.5
- webpack Version: v4
- compression-webpack-plugin Version: v7.0.0

### Expected Behavior
Should not throw error while building the project

### Actual Behavior
throwing error on running webpack for build
Error: `Cannot read property 'tapPromise' of undefined`

### Code
I am using `cra` with `customize-cra` and `react-app-rewired`
```js
addWebpackPlugin(new CompressionPlugin())
```

### How Do We Reproduce?
1. Run new app using `cra`
2. Install `customize-cra`, `react-app-rewired` and `compression-webpack-plugin`
3. add `config-overrides.js` on root level and add following code to it
```js
const CompressionPlugin = require('compression-webpack-plugin');
const { override, addWebpackPlugin } = require('customize-cra');
module.exports = override(addWebpackPlugin(new CompressionPlugin()));
```
4. change build script to `react-app-rewired build` and execute it.

**Comment by danieletulone** [comment]
Same error with a vue project.
I'm fixed making downgrade to ^6.0.0.

In package.json change the version from ^7.0.0 and replace with ^6.0.0. Then run `npm install`.

**Comment by afzaalahmad** [comment]
@danieletulone for the time being, I downgraded my version to 6. But downgrading is not a solution of this bug.

**Comment by alexander-akait** [comment]
You need webpack@5 to use latest version, please respect time of other developers and read CHANGELOG before update

**Comment by nanyang24** [comment]
Your webpack version is v4
so the compression-webpack-plugin needs to be under v7
