### ISSUE TITLE
Cannot find module "compression-webpack-plugin"

### ISSUE THREAD

**Issue by ev1stensberg** [webpack-contrib/compression-webpack-plugin#23]
Is this plugin outdated?

**Comment by iGitScor** [comment]
Did you install it ? Is it added to your `package.json` ?

I didn't have any issue by installing it today

**Comment by michael-ciniawsky** [comment]
@ev1stensberg Please reopen if it shouldn't be resolved, assuming it is  😛

**Comment by ev1stensberg** [comment]
@michael-ciniawsky So long time ago, I can't even remember what I was trying to do in the first place 😆
