### ISSUE TITLE
The "deleteOriginalAssets: true" option does not work in v7.0.0

### ISSUE THREAD

**Issue by Fa-So** [webpack-contrib/compression-webpack-plugin#231]
Issue 🔥

If the option `deleteOriginalAssets: true` is used, then it ends with the error message
`UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'source' of undefined`

With the `compression-webpack-plugin` **v6.1.1** everything works as expected.

- Operating System: Windows
- Node Version: 14.13.1
- NPM Version: 6.14.8
- webpack Version: 5.10.0
- compression-webpack-plugin Version: 7.0.0

### Expected Behavior
Delete the original assets

### Code
```js
// webpack.config.js
    new CompressionPlugin({
      deleteOriginalAssets: true
    }),
```
### How Do We Reproduce?
Just set the option

**Comment by alexander-akait** [comment]
Can't reproduce, please create reproducible test repo and I will reopen it

**Comment by alexander-akait** [comment]
Try https://github.com/webpack-contrib/compression-webpack-plugin/releases/tag/v7.1.1, maybe related
