### ISSUE TITLE
Missing a certain changes(include 0.1.0，0.1.1 and 3.0.1) in CHANGELOG.md

### ISSUE THREAD

**Issue by liuliangsir** [webpack-contrib/compression-webpack-plugin#238]
Documentation Is:

- [x] Missing
- [ ] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
As the above title says, It seem to be missing a certain changes about 0.1.0，0.1.1 and 3.0.1

### Your Proposal for Changes
Add the missings back to CHANGELOG.md

**Comment by alexander-akait** [comment]
We don't have changelog generation for this versions, also it is very old, no need to fix it
