### ISSUE TITLE
Build error with webpack@4.44.1

### ISSUE THREAD

**Issue by reversefuture** [webpack-contrib/compression-webpack-plugin#239]
I'm useing compression-webpack-plugin@5.0.1 to compress webpack building assets, but each time I build I got below error:

`ModuleNotFoundError: Module not found: Error: Can't resolve 'module' in '\demo\node_modules\webpack\lib'`

In compression-webpack-plugin@7.1.1, I got below error:
` ERROR  TypeError: Cannot read property 'tapPromise' of undefined`

Any suggestions with above errors?

**Comment by alexander-akait** [comment]
Because latest version compatibility only with webpack@5, please read CHANGELOG **carefully**

**Comment by LiuduZero** [comment]
@alexander-akait  excuse, but I use the old version (5.0.2), webpack is @vue/cli-plugin-babel@4.5.17----webpack@4.46.0 , is appear `Module not found: Error: Can't resolve 'module'`

**Comment by alexander-akait** [comment]
You need 4 version for old webpack

**Comment by LiuduZero** [comment]
I think it`s very, strange, when I build another project with vesion `^4`, it work well

**Comment by alexander-akait** [comment]
Try to update webpack version, to the latest stable v4

**Comment by LiuduZero** [comment]
Oh I'm so sorry, version `^6.1.1` or `^4` is ok, last times work bad becauce anther reason

vue.config.js is quoted by sourceFile like entry.js

vue.config.is
```
module.exports = {}
```

sourceFile
```
import config from '../vue.config.js'
// const config = require('../vue.config.js)

that all cause the error
```
![image](https://user-images.githubusercontent.com/24452177/170100876-5e62c2bc-e53e-4c9a-bd72-8e8af4dd66ab.png)


Thanks for you help very much!

**Comment by LiuduZero** [comment]
Good night

**Comment by zhangshuai0101** [comment]
> Oh I'm so sorry, version `^6.1.1` or `^4` is ok, last times work bad becauce anther reason
> 
> 哦，我很抱歉，版本 ^ 6.1.1或 ^ 4是好的，上次工作不好，因为另一个原因
> 
> vue.config.js is quoted by sourceFile like entry.js
> 
> SourceFile 像 entry.js 一样引用 vue.config.js
> 
> vue.config.is
> 
> ```
> module.exports = {}
> ```
> 
> sourceFile
> 
> 来源文件
> 
> ```
> import config from '../vue.config.js'
> // const config = require('../vue.config.js)
> 
> that all cause the error
> ```
> 
> ![image](https://user-images.githubusercontent.com/24452177/170100876-5e62c2bc-e53e-4c9a-bd72-8e8af4dd66ab.png)
> 
> Thanks for you help very much!
> 
> 非常感谢你的帮助！

请问您是怎么解决的？目前我也是一直在报这个错误，版本使用的6.1.1
