### ISSUE TITLE
HookWebpackError: filenameForRelatedName.indexOf is not a function

### ISSUE THREAD

**Issue by gqgs** [webpack-contrib/compression-webpack-plugin#240]
- compression-webpack-plugin Version: 7.1.1

### Expected Behavior

The plugin to compress data as expected.

### Actual Behavior

webpack crashes wtih a HookWebpackError after the plugin tries to access the `indexOf` of a function.

```
HookWebpackError: filenameForRelatedName.indexOf is not a function
```

### Code

```js
// webpack.config.js

const zopfli = require("@gfx/zopfli");

module.exports = {
  plugins: [
    new CompressionPlugin({
        filename(pathData) {
            // other things here...
            return "[path][name].gz";
        },
        algorithm(input, compressionOptions, callback) {
            return zopfli.gzip(input, compressionOptions, callback);
        },
    }),
  ],
};

```

### How Do We Reproduce?

Apparently it happens if `algorithm` and `filename` properties are both defined as functions.
I could be missing something but it seems the case where `filename` is a function is being ignored in the section bellow.

https://github.com/webpack-contrib/compression-webpack-plugin/blob/44c16e2bc83f6c7f282b828729b4288e74fdb980/src/index.js#L128-L131

**Comment by alexander-akait** [comment]
Yep, bug

**Comment by alexander-akait** [comment]
Just interesting - why do you use it as function?

**Comment by gqgs** [comment]
@alexander-akait I'm using a different `algorithm` and `filename` functions. I just used that from the docs since it'd be easier to reproduce/understand.

**Comment by alexander-akait** [comment]
Yep, I will fix it tomorrow, thanks for the issue

**Comment by gqgs** [comment]
@alexander-akait Thank you.
