### ISSUE TITLE
An error occurred during the build: TypeError: Cannot read property 'tapPromise' of undefined

### ISSUE THREAD

**Issue by Alecto** [webpack-contrib/compression-webpack-plugin#242]
- Operating System: windows 10
- Node Version: 14.15.4
- NPM Version: 6.14.10
- webpack Version:  webpack  5? (default for angular 11)
- compression-webpack-plugin Version: 7.1.2

### extra-webpack.config.js

```js

const CompressionPlugin = require('compression-webpack-plugin');

module.exports = (config) => {
  if (config.mode !== 'development') {
    config.plugins.push(new CompressionPlugin());
  }

  return config;
}

```

![image](https://user-images.githubusercontent.com/8464662/105141238-86d2f800-5b01-11eb-8e95-a42c5327cecf.png)

i use  "@angular-builders/custom-webpack": "^11.0.0"

### angular.json
![image](https://user-images.githubusercontent.com/8464662/105141388-baae1d80-5b01-11eb-9dea-b99fb7895222.png)

@angular-builders/custom-webpack works correctly and correctly and the error only appears when adding CompressionPlugin

**Comment by alexander-akait** [comment]
You need webpack@5 to use this plugin, please read CHANGELOG before updating, `@angular-builders/custom-webpack` can still use webpack@4

**Comment by tswaters** [comment]
I came here via the webpack docs.

When selecting version 4 of the docs, this page is displayed:  https://v4.webpack.js.org/plugins/compression-webpack-plugin/

Which appears to inject the latest readme from this repository.

Would it be possible to include a disclaimer near the top of this file that indicates the supported webpack versions?  

Gleaning the CHANGELOG -- v7.0.0 -> drops webpack 4 support
