### ISSUE TITLE
Suggestion: Loosen webpack peer dependency

### ISSUE THREAD

**Issue by thenoseman** [webpack-contrib/compression-webpack-plugin#248]
- Operating System: MacOs Catalina 10.15.7
- Node Version: v15.14.0
- NPM Version: 7.10.0
- webpack Version: > 5.1.x
- compression-webpack-plugin Version: > 6.1.1

### Expected Behavior / Situation
Updating an vue app from webpack4 to webpack5.
Updating packages to versions using webpack 5 should update to a compatible webpack 5.* version.

### Actual Behavior / Situation
Lot's of plugins require different versions of webpack which are *not* incompatible on the software side but just incompatible on the *npm specification*  side.

eg. this plugin has:
```
"peerDependencies": {
    "webpack": "^5.1.0"
  },
```
This doesn't allow me to update to webpack 5.33.x even though it seems compatible (tests pass).

### Modification Proposal
Perhaps it is possible to specify the `peerDependency` as `>= 5.1.0` as stated in the [changelog](CHANGELOG.md#-breaking-changes)?
This would allow updating.

Thanks for your hard work on this, very much appreciated!

**Comment by alexander-akait** [comment]
`^5.1.0` means `5.1.0` and above, Can you clarify what is the problem?

**Comment by thenoseman** [comment]
You are totally right and I'm totally wrong :)
Sorry. Mistook it for `~`.

Then I have to look elsewhere. Thanks!
