### ISSUE TITLE
@types/compression-webpack-plugin for Webpack 5

### ISSUE THREAD

**Issue by dko-slapdash** [webpack-contrib/compression-webpack-plugin#254]
Hi.

Currently, @types/compression-webpack-plugin is incompatible with webpack 5 typing - Compiler type is different.

**Comment by alexander-akait** [comment]
Please open an issue in https://github.com/DefinitelyTyped/DefinitelyTyped, in near future we want implement ts support out of box, but problem with @types/compression-webpack-plugin we can't solve here

**Comment by nickensoul** [comment]
Hey. FYI: I've just [created a discussion topic](https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/54412) about this problem in the DefinitelyTyped's discussion board.
