### ISSUE TITLE
TypeError: Cannot read property 'tapPromise' of undefined

### ISSUE THREAD

**Issue by qqii3184** [webpack-contrib/compression-webpack-plugin#261]
- Operating System:  Windows 10
- Node Version: 14.17.4
- NPM Version: 6.14.14
- webpack Version: 5.49.0
- compression-webpack-plugin Version: 8.0.1

### Expected Behavior

- use compression-webpack-plugin to open gzip support.

### Actual Behavior

I install  compression-webpack-plugin with npm , and write code in vue.config.js
then run order : npm run build
Console show the Error : TypeError: Cannot read property 'tapPromise' of undefined
at \node_modules\compression-webpack-plugin\dist\index.js:283:30

### Code

```js
const CompressionWebpackPlugin = require('compression-webpack-plugin')
const productionGzipExtensions = /\.(js|css|json|txt|html|ico|svg)(\?.*)?$/i;
module.exports = {
configureWebpack : config =>{
      const plugins = [];
      plugins.push(
        new CompressionWebpackPlugin({
          filename: "[path].gz[query]",
          algorithm: "gzip",
          test: productionGzipExtensions,
          threshold: 10240,
          minRatio: 0.8
        })
      );
      config.plugins = [...config.plugins,...plugins];
    }
}
```

I test lower version like 8.0.0、7.1.2  , has the same error.

when I use 6.1.1 ,it worked .

**Comment by alexander-akait** [comment]
run `npm ls webpack`, you still on webpack v4, sorry can't be fixed here

**Comment by LiuduZero** [comment]
> * Operating System:  Windows 10
> * Node Version: 14.17.4
> * NPM Version: 6.14.14
> * webpack Version: 5.49.0
> * compression-webpack-plugin Version: 8.0.1
> 
> ### Expected Behavior
> * use compression-webpack-plugin to open gzip support.
> 
> ### Actual Behavior
> I install compression-webpack-plugin with npm , and write code in vue.config.js then run order : npm run build Console show the Error : TypeError: Cannot read property 'tapPromise' of undefined at \node_modules\compression-webpack-plugin\dist\index.js:283:30
> 
> ### Code
> ```js
> const CompressionWebpackPlugin = require('compression-webpack-plugin')
> const productionGzipExtensions = /\.(js|css|json|txt|html|ico|svg)(\?.*)?$/i;
> module.exports = {
> configureWebpack : config =>{
>       const plugins = [];
>       plugins.push(
>         new CompressionWebpackPlugin({
>           filename: "[path].gz[query]",
>           algorithm: "gzip",
>           test: productionGzipExtensions,
>           threshold: 10240,
>           minRatio: 0.8
>         })
>       );
>       config.plugins = [...config.plugins,...plugins];
>     }
> }
> ```
> 
> I test lower version like 8.0.0、7.1.2 , has the same error.
> 
> when I use 6.1.1 ,it worked .
> 
> ### How Do We Reproduce?

when I use 6.1.1, it appear the error like this
```
This dependency was not found:
* module in (webpack)/lib/NormalModule.js, (webpack)/lib/node/NodeTargetPlugin.js
To install it, you can run: npm install --save module
```

when I try the older version, its the same error like above

**Comment by LiuduZero** [comment]
@qqii3184 
when I use 6.1.1, it appear the error like this
```
This dependency was not found:
* module in (webpack)/lib/NormalModule.js, (webpack)/lib/node/NodeTargetPlugin.js
To install it, you can run: npm install --save module
```
when I try the older version, its the same error like above

**Comment by yogithesymbian** [comment]
> run `npm ls webpack`, you still on webpack v4, sorry can't be fixed here

so there is no alternative for our webpack v4 ? maybe using older version of webpack compression plugin ? 
the latest version is `"compression-webpack-plugin": "^10.0.0",`
and my engine
```
➜  yogi git:(master) ✗ npm ls webpack
yogiaw@15.2.2 /Users/yogiarifwidodo/Sites/YOGI/yogi
├─┬ @vue/cli-plugin-babel@4.5.15
│ └── webpack@4.46.0 
├─┬ @vue/cli-plugin-eslint@4.5.15
│ └── webpack@4.46.0  deduped
└─┬ @vue/cli-service@4.5.15
  └── webpack@4.46.0  deduped
```
