### ISSUE TITLE
Changes input filenames when used in conjuction with webpack-manifest-plugin

### ISSUE THREAD

**Issue by colorninja** [webpack-contrib/compression-webpack-plugin#267]
### Bug report
When used together with webpack-manifest-plugin, it changes the input filenames to add .gz, which kind of defeats the purpose of having a the manifest file. The manifest plugin works correctly when used without the compression plugin.

It's quite inconvenient when reading from the manifest and having non-compressed development version and compressed production version.

### Actual Behavior
```json
{
  "main.js.gz": "/main.825ccd2a8b9054292614.js.gz",
  "main.css.gz": "/main.825ccd2a8b9054292614.css.gz"
}
```

### Expected Behavior

```json
{
  "main.js": "/main.825ccd2a8b9054292614.js.gz",
  "main.css": "/main.825ccd2a8b9054292614.css.gz"
}
```

### How Do We Reproduce?

Minimal reproduction: https://github.com/colorninja/compression-webpack-plugin-bug

1. Run `yarn` to install dependencies
2. Run `yarn without`
3. Check the keys in `build-manifest.json`
4. Run `yarn with`
5. Check the keys in `build-manifest.json`

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
```
  System:
    OS: Linux 5.11 Alpine Linux
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 6.83 GB / 30.99 GB
  Binaries:
    Node: 14.18.1 - /tmp/yarn--1635780013939-0.3314735302212355/node
    Yarn: 1.22.10 - /tmp/yarn--1635780013939-0.3314735302212355/yarn
  Packages:
    babel-loader: ^8.2.3 => 8.2.3 
    compression-webpack-plugin: ^9.0.0 => 9.0.0 
    css-loader: ^6.5.0 => 6.5.0 
    dotenv-webpack: ^7.0.3 => 7.0.3 
    file-loader: ^6.2.0 => 6.2.0 
    ignore-loader: ^0.1.2 => 0.1.2 
    resolve-url-loader: ^4.0.0 => 4.0.0 
    sass-loader: ^12.3.0 => 12.3.0 
    style-loader: ^3.3.1 => 3.3.1 
    ts-loader: ^9.2.6 => 9.2.6 
    webpack: ^5.61.0 => 5.61.0 
    webpack-bundle-analyzer: ^4.5.0 => 4.5.0 
    webpack-cli: ^4.9.1 => 4.9.1 
    webpack-manifest-plugin: ^4.0.2 => 4.0.2 
    webpack-merge: ^5.8.0 => 5.8.0 
    webpack-s3-plugin: ^1.2.0-rc.0 => 1.2.0-rc.0 
```

**Comment by alexander-akait** [comment]
Please open this in `WebpackManifestPlugin` repo

**Comment by alexander-akait** [comment]
You should not use `.gz` in HTML, CSS, JS, it is invalid, if you need this for serer purposes, it is out of scope this plugin and should be done by `WebpackManifestPlugin`
