### ISSUE TITLE
[types] `@gfx/zopfli` can't be used with new types

### ISSUE THREAD

**Issue by vitoyucepi** [webpack-contrib/compression-webpack-plugin#274]
### Bug report
New types from `compression-webpack-plugin@9.1.1` are not compatible with `@gfx/zopfli`.
With `@types/compression-webpack-plugin@9.0.0` and `compression-webpack-plugin@9.1.0` it works fine.

### Actual Behavior
With `compression-webpack-plugin@9.1.1` zopfli can't be used as compression algorithm
```ts
new CompressionPlugin({
	algorithm: gzip,
	compressionOptions: {
		numiterations: 15
	}
})
```
produces errors:
```
index.ts:5:2 - error TS2322: Type '(buffer: InputType, options: ZopfliOptions, cb: OnCompressComplete) => void' is not assignable to type 'string | AlgorithmFunction<ZlibOptions> | undefined'.
  Type '(buffer: InputType, options: ZopfliOptions, cb: OnCompressComplete) => void' is not assignable to type 'AlgorithmFunction<ZlibOptions>'.
    Types of parameters 'options' and 'options' are incompatible.
      Type 'ZlibOptions' has no properties in common with type 'ZopfliOptions'.

5  algorithm: gzip,
   ~~~~~~~~~

index.ts:7:3 - error TS2322: Type '{ numiterations: number; }' is not assignable to type 'ZlibOptions'.
  Object literal may only specify known properties, and 'numiterations' does not exist in type 'ZlibOptions'.

7   numiterations: 15
    ~~~~~~~~~~~~~~~~~
```

### Expected Behavior
New types should support `zopfli` types in addition to standard settings, because it's advertised as compatible.

### How Do We Reproduce?
1. `yarn init`, use defaults
1. `yarn add typescript`
1. `yarn tsc --init`, use defaults
1. `yarn add webpack`
1. `yarn add compression-webpack-plugin`
1. `yarn add @gfx/zopfli`
1. Create `index.ts`
   ```ts
   import CompressionPlugin from 'compression-webpack-plugin';
   import {gzip} from '@gfx/zopfli';

   const b = new CompressionPlugin({
     algorithm: gzip,
     compressionOptions: {
       numiterations: 15
     }
   })
   console.log(b)
   ```
1. `yarn tsc`

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
Not related

**Comment by alexander-akait** [comment]
We are generic type, please use:
```
new CompressionPlugin<ZopfliOptions>({
	algorithm: gzip,
	compressionOptions: {
		numiterations: 15
	}
})
```

**Comment by alexander-akait** [comment]
But I see some incompatibilities, I will fix it

**Comment by alexander-akait** [comment]
https://github.com/webpack-contrib/compression-webpack-plugin/pull/275
