### ISSUE TITLE
gzipped css not updated in html file

### ISSUE THREAD

**Issue by guestisp** [webpack-contrib/compression-webpack-plugin#299]
v9.2.0

With the following configuration:
```
    new CompressionPlugin({
      deleteOriginalAssets: true,
      exclude: 'index.html'
    }),
```

and this *original* `index.html` file:
```
<!DOCTYPE html>
<html class="has-background-light">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <script type="text/javascript" src="/js/force_provisoning.js"></script>
    <link rel="icon" type="image/x-icon" href="/favicon.png">
  </head>
  <body>
    <div id="app"></div>
    <!-- built files will be auto injected -->
  </body>
</html>
```

the CSS bundle file is compressed as expected:
```
$ npm run build

> x@1.0.0 build /media/x/I miei file/GIT/x/web
> webpack --config config/webpack.prod.js

asset js/main.4889de88769f.bundle.js.gz 254 KiB [emitted] [immutable] [compressed]
asset styles/main.328b6632c1e3.css.gz 47.9 KiB [emitted] [immutable] [compressed]
asset 9b0eb6a1904664ed1f87.png 4.43 KiB [emitted] [immutable] [from: src/assets/logo.png] (auxiliary name: main)
asset js/runtime.2cb9942e37d1.bundle.js.gz 756 bytes [emitted] [immutable] [compressed]
asset index.html 521 bytes [emitted]
asset assets/.gitkeep 0 bytes [emitted] [from: static/.gitkeep] [copied]
```

but the resulting index file is not updated, still referes to the uncompressed version:
```
<!doctype html><html class="has-background-light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><script src="/js/force_provisoning.js"></script><link rel="icon" type="image/x-icon" href="/favicon.png"><script defer="defer" src="/js/runtime.2cb9942e37d1.bundle.js"></script><script defer="defer" src="/js/main.4889de88769f.bundle.js"></script><link href="/styles/main.328b6632c1e3.css" rel="stylesheet"></head><body><div id="app"></div></body></html>
```

**Comment by alexander-akait** [comment]
Because browser doesn't support `.gz`, it is for server, when browser ask `main.328b6632c1e3.css`, server will look `main.328b6632c1e3.css.gz` in directory and will use it for `main.328b6632c1e3.css`, you should not have `.gz` in `html` files

**Comment by guestisp** [comment]
Well, I have .gz on ALL files in the html except one, so there is something wrong anyway. Look at the un-minified index:
```
<!doctype html>
<html class="has-background-light">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="/js/force_provisoning.js"></script>
    <link rel="icon" type="image/x-icon" href="/favicon.png">
    <script defer="defer" src="/js/runtime.2cb9942e37d1.bundle**.js**"></script>
    <script defer="defer" src="/js/main.4889de88769f.bundle**.js**"></script>
    <link href="/styles/main.328b6632c1e3.css" rel="stylesheet">
  </head>
  <body>
    <div id="app"></div>
  </body>
</html>
```

as you can see, other files have `.gz` extension (and browsers are able to handle them, anyway) 
If this is not an expected behaviour, you should not update webpack assets list with the new names or other plugins will get the gzipped name: https://github.com/webpack-contrib/compression-webpack-plugin/blob/master/src/index.js#L374-L390

But the issue still exists, why just one file is left not updated ?

**Comment by alexander-akait** [comment]
I don't see `.gz` in your HTML file

**Comment by guestisp** [comment]
Pardon, wrong post. This is the correct one:
```
<!doctype html>
<html class="has-background-light">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="/js/force_provisoning.js"></script>
    <link rel="icon" type="image/x-icon" href="/favicon.png">
    <script defer="defer" src="/js/runtime.2cb9942e37d1.bundle.js.gz"></script>
    <script defer="defer" src="/js/main.4889de88769f.bundle.js.gz"></script>
    <link href="/styles/main.328b6632c1e3.css" rel="stylesheet">
  </head>
  <body>
    <div id="app"></div>
  </body>
</html>
```

Seems to change after build. that's why i've thought in a race condition, based on when the html plugin starts. But i'm unsure, what i know is that I have to handle both files (with an without .gz) with a regex

**Comment by alexander-akait** [comment]
You can't use `.gz` in `src` for `script`, same for CSS, yes, you can setup server to handle it, but it sounds invalid

**Comment by guestisp** [comment]
Ok, but why some files are wrote gzipped in the index.html ? 
It's ok to have all *.gz or without .gz but they should be al the same.

**Comment by guestisp** [comment]
https://webpack.js.org/plugins/html-webpack-plugin/

**Comment by alexander-akait** [comment]
What is webpack version? Can you fill out an issue template to avoid unnecessary questions?

**Comment by guestisp** [comment]
v5. i'll post the missing info tomorrow

**Comment by guestisp** [comment]
> What is webpack version? Can you fill out an issue template to avoid unnecessary questions?

updated the first post.

**Comment by alexander-akait** [comment]
I think bug in `optimize-css-assets-webpack-plugin`, please migrate to https://github.com/webpack-contrib/css-minimizer-webpack-plugin

**Comment by guestisp** [comment]
It's not used, was here before upgrading from webpack v3 and never removed but i'm using `css-minimizer-webpack-plugin: ^3.4.1 => 3.4.1` as you can see in the report.

anyway, i've uninstalled the old garbage.

**Comment by alexander-akait** [comment]
You should not have `.gz` files in HTML, If you provide reproducible test repo I will look

**Comment by KristinaB162** [comment]
In my index.html the script tags are completely missing when the property "deleteOriginalAssets" is true. Described in the mentioned issue above. 
At the moment i use a postbuild to delete all not compressed files after compression (with deleteOriginalAssets on false).
