### ISSUE TITLE
Decompression problem

### ISSUE THREAD

**Issue by pavankumarkatakam** [webpack-contrib/compression-webpack-plugin#32]
If we compress the static content before the browser asks, some browsers doesnt know how to decompression then their may be a problem. I haven't used this just though of this problem.

**Comment by prewk** [comment]
http://webmasters.stackexchange.com/questions/22217/which-browsers-handle-content-encoding-gzip-and-which-of-them-has-any-special

**Comment by michael-ciniawsky** [comment]
@prewk Thx
