### ISSUE TITLE
ERROR in Conflict: Multiple assets emit different content to the same filename css/.gz

### ISSUE THREAD

**Issue by sushmitg** [webpack-contrib/compression-webpack-plugin#341]
I am upgrading to webpack 5 and as per the official doc, we need to upgrade all the plugins and loaders to their latest version.
So, I updated my compression-webpack-plugin to v10. But now while creating a production build I am getting following error:

<img width="542" alt="image" src="https://user-images.githubusercontent.com/22211683/215971623-7d54a7ef-d3e8-47e7-bcd1-8a919fd89f0b.png">

### Here's my configuration:
```
    new CompressionPlugin({
      filename: '[path].gz[query]',
      algorithm: 'gzip',
      test: /\.js$|\.css$|\.html$/,
      threshold: 10240,
      minRatio: 0.8,
    }),
```

Am I missing anything?

**Comment by alexander-akait** [comment]
Hello, please read https://github.com/webpack-contrib/compression-webpack-plugin#string-1

> [path] is replaced with the directories to the original asset, included trailing / (assets/images/).

You should add `[base] is replaced with the base ([name] + [ext]) of the original asset (image.png).`, i.e. ` filename: "[path][base].gz[query]",`
