### ISSUE TITLE
How to do this compression from express?

### ISSUE THREAD

**Issue by ktae1399** [webpack-contrib/compression-webpack-plugin#349]
I have compressed with this webpack configuration. How can I achieve this same from express server.js file and by running a command from package.json I need to achieve this for production.

**Comment by alexander-akait** [comment]
You can use this https://github.com/pirxpilot/connect-gzip-static, but many developers use nginx (or another proxy server), you can setup it for nginx http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html
