### ISSUE TITLE
[Request] Release version 0.3.2 to npmjs.org

### ISSUE THREAD

**Issue by GregOnNet** [webpack-contrib/compression-webpack-plugin#35]
Hey guys,

can you publish version 0.3.2 of  `compression-webpack-plugin` to npmjs.org, please?
I have an issue installing `angular-cli` on windows machines because references `compression-webpack-plugin` as Git-Repository. This leads into problems with `Cygwin Git`.

For further information please refer to https://github.com/angular/angular-cli/issues/2394.

**Comment by TheLarkInn** [comment]
@sokra when you get a second, shoot me the rights over and I'll cut a release

**Comment by cDecker32** [comment]
Just an FYI, though the issue specified in the OP is now closed. There are a lot of people using angular-cli that this is causing problems for. Please cut a release over to npm asap.

**Comment by TheLarkInn** [comment]
Thank you for an update, I've been working to have these privileges granted so this doesn't happen in the future. Please bear with us as the original author is on vacation.

**Comment by sokra** [comment]
Added you to npm

**Comment by TheLarkInn** [comment]
```
n on git:master ● [13:40:12]
→ npm publish ./
+ compression-webpack-plugin@0.3.2
```

Done!!!! Enjoy!! Sorry for the delay. I'd close the issue but I can't currently. :joy:

**Comment by cDecker32** [comment]
Awesome! Thanks!

**Comment by nertzy** [comment]
Please add a tag so that it shows up in the GitHub releases as well. Thanks!
