### ISSUE TITLE
Version 6 (for Webpack 4) does not work on Node 18+

### ISSUE THREAD

**Issue by renchap** [webpack-contrib/compression-webpack-plugin#364]
### Bug report

When running Webpack 4 with the latest version of this plugin on Node 18 (thanks to the new Webpack 4 version), it fails with this error:
```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at /Users/renchap/dev/mastodon/mastodon/node_modules/compression-webpack-plugin/dist/index.js:230:42
    at CompressionPlugin.compress (/Users/renchap/dev/mastodon/mastodon/node_modules/compression-webpack-plugin/dist/index.js:319:9)
    at /Users/renchap/dev/mastodon/mastodon/node_modules/compression-webpack-plugin/dist/index.js:340:12
    at _next1 (eval at create (/Users/renchap/dev/mastodon/mastodon/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:37:17)
    at eval (eval at create (/Users/renchap/dev/mastodon/mastodon/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:64:1)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Actual Behavior

Build fails with the error above

### Expected Behavior

The build should complete without error on Node 18

### How Do We Reproduce?

This can be reproduced on Mastodon with this PR: https://github.com/mastodon/mastodon/pull/26830 (look at the failed github actions)

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

Webpack version 4.47.0
`compression-webpack-plugin` version 6.1.1 (latest version compatible with Webpack 4)

**Comment by renchap** [comment]
Pinging @TheLarkInn as you merged https://github.com/webpack/webpack/pull/17628

**Comment by BossMAN559** [comment]
before the precompile execute this command
export NODE_OPTIONS=--openssl-legacy-provider

**Comment by renchap** [comment]
Yes this kind of fixes the issue, but the intend for https://github.com/webpack/webpack/pull/17628 is to avoid this and allow Webpack 4 to run on Node 18 without those changes.

I think this could be fixed by requiring Webpack 4.47.0 and using `import { createHash } from "webpack/lib/util/createHash"` to replace `crypto.createHash`, but I am not sure how to send a PR for this as there is no stable branch for version 6.

**Comment by BossMAN559** [comment]
i look forward to not needing to run the export.

**Comment by renchap** [comment]
I can confirm that applying this patch over the 6.1.1 version works with Node 18:

```
From 89b18c66f0c37f7d4dbb9ce774632515baf643bc Mon Sep 17 00:00:00 2001
From: Renaud Chaput <renchap@gmail.com>
Date: Thu, 7 Sep 2023 01:11:45 +0200
Subject: [PATCH] Add compatibility with Node 18+

---
 package.json | 2 +-
 src/index.js | 4 ++--
 2 files changed, 3 insertions(+), 3 deletions(-)

diff --git a/package.json b/package.json
index 3b68a99..82d50ab 100644
--- a/package.json
+++ b/package.json
@@ -38,7 +38,7 @@
     "dist"
   ],
   "peerDependencies": {
-    "webpack": "^4.0.0 || ^5.0.0"
+    "webpack": "^4.47.0 || ^5.0.0"
   },
   "dependencies": {
     "cacache": "^15.0.5",
diff --git a/src/index.js b/src/index.js
index cccccd4..45e1bcc 100644
--- a/src/index.js
+++ b/src/index.js
@@ -3,13 +3,13 @@
   Author Tobias Koppers @sokra
 */
 
-import crypto from "crypto";
 import path from "path";
 
 import webpack, {
   ModuleFilenameHelpers,
   version as webpackVersion,
 } from "webpack";
+import { createHash } from "webpack/lib/util/createHash";
 import { validate } from "schema-utils";
 import serialize from "serialize-javascript";
 
@@ -229,7 +229,7 @@ class CompressionPlugin {
               originalAlgorithm: this.options.algorithm,
               compressionOptions: this.options.compressionOptions,
               name,
-              contentHash: crypto.createHash("md4").update(input).digest("hex"),
+              contentHash: createHash("md4").update(input).digest("hex"),
             };
           } else {
             cacheData.name = serialize({
-- 
2.42.0

```

I am not sure how I can submit a PR for this, or if the maintainers can easily make a new v6 release.

I updated the peer deps to require the latest Webpack 4 version, as this is the one exporting `createHash`.

**Comment by renchap** [comment]
I forked the repository and added a commit that makes the plugin work with Webpack 4 and Node 18+ (tested with Node 18 and Node 20 on Mastodon, see https://github.com/mastodon/mastodon/pull/26830).

You can find the related changes here: https://github.com/renchap/compression-webpack-plugin/commit/a98a929c72dd6ea2ef84c353aef916eee7a11cde

The `package.json` has been updated to require Webpack 4.47, as this is the version including the new `createHash` function.

This is published on NPM as [`@renchap/compression-webpack-plugin`](https://www.npmjs.com/package/@renchap/compression-webpack-plugin)

It would be very welcome for a maintainer of this package to use this patch and release an official 6.1.2 version, so people stuck on Webpack 4 can upgrade to a supported Node version.

**Comment by snitin315** [comment]
We'll do a patch release.

**Comment by ClearlyClaire** [comment]
> We'll do a patch release.

Thanks! Any estimate for when this will happen?

**Comment by alexander-akait** [comment]
Fixed https://github.com/webpack-contrib/compression-webpack-plugin/pull/373, release will be soon

**Comment by alexander-akait** [comment]
Please try https://github.com/webpack-contrib/compression-webpack-plugin/releases/tag/v6.1.2, sorry for delay
