### ISSUE TITLE
compression-webpack-plugin  .woff compression is not supported

### ISSUE THREAD

**Issue by me1129** [webpack-contrib/compression-webpack-plugin#383]
Node Version: v16.17.0
webpack Version: 5.90.2
compression-webpack-plugin Version: 6.1.1
### Bug report
![image](https://github.com/webpack-contrib/compression-webpack-plugin/assets/20635846/47243168-e09e-4343-b365-76feb034ae99)
![image](https://github.com/webpack-contrib/compression-webpack-plugin/assets/20635846/f0545c18-6a1e-49ef-8ee7-486ad6515bfe)

**Comment by alexander-akait** [comment]
Please fill out all fields, I will reopen when you fixed it

**Comment by me1129** [comment]
> Please fill out all fields, I will reopen when you fixed it

OK，I have updated

**Comment by alexander-akait** [comment]
Please fill out this

> How Do We Reproduce?
