### ISSUE TITLE
How to use/render bundle.js.gz in html file

### ISSUE THREAD

**Issue by chandrasekarb** [webpack-contrib/compression-webpack-plugin#40]
webpack.config.js

```

var CompressionPlugin = require('compression-webpack-plugin');
/*...................................*/
  output: {
    path: PROD ? path.resolve(ROOT_PATH, 'dist') :
      path.resolve(ROOT_PATH, 'app/build'),
    publicPath: '/',
    filename: 'bundle.js',
  },
/*....................................*/
    new CompressionPlugin({
      asset: "[path].gz[query]",
      algorithm: "gzip",
      test: /\.js$|\.css$|\.html$/,
      threshold: 10240,
      minRatio: 0.8
    })
/*....................................*/

```

server.js

```
const serve = require('koa-static');
const send = require('koa-send');
const koa = require('koa');
const app = koa();
app.use(serve(__dirname + '/app/build'));
app.use(function* index() {
  yield send(this, './app/build/index.html');
});
app.listen(9090);
console.log("listening on 9090");
```

output files:

vendor.bundle.js        1.38 MB       0  [emitted]  vendor
bundle.js         943 kB       1  [emitted]  app
vendor.bundle.js.map        9.83 MB       0  [emitted]  vendor
bundle.js.map        4.13 MB       1  [emitted]  app
bundle.js.gz         165 kB          [emitted]  
vendor.bundle.js.gz         361 kB          [emitted]  
index.html      323 bytes          [emitted]  

index.html   ( is the following code is correct to render the above build files)

```

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>myapp</title>
  </head>
  <body>
    <div id="app"></div>
     <script src="/vendor.bundle.js.gz"></script>
    <script src="/bundle.js.gz"></script>
  </body>
</html>

```

Unable to render my app page by using the above code, is the above index.html code is correct to render the build files

**Comment by TomDeBacker** [comment]
Try removing the .gz. You should have a look at this plugin aswell:
 https://github.com/jantimon/html-webpack-plugin

**Comment by michael-ciniawsky** [comment]
@chandrasekarb  https://github.com/koajs/static#options You need to explicitly enable GZIP serving in koa-static via options.gzip

**Comment by tarim** [comment]
@chandrasekarb any luck? I have same issue, It doesn't work for me at all. 

any suggestion please?

![image](https://cloud.githubusercontent.com/assets/453087/25661584/3f4c2124-2fdf-11e7-9727-61e5017d7409.png)

Thank you,

NS

**Comment by hnqdarktime** [comment]
Try this:
```
const serve = require('koa-static');
const send = require('koa-send');
const koa = require('koa');
const app = koa();

**app.use('/app/build', function (req, res, next) {
  res.set('Content-Encoding', 'gzip');
  next();
});**

app.use(serve(__dirname + '/app/build'));
app.use(function* index() {
  yield send(this, './app/build/index.html');
});
app.listen(9090);
console.log("listening on 9090");
```
