### ISSUE TITLE
what is for?

### ISSUE THREAD

**Issue by zzzgit** [webpack-contrib/compression-webpack-plugin#43]
Hello,I want to ask that what's this plugin for?
As the web server have the functionality to serve files in a compressed format,is it necessary to use this plugin to convert the file format?

**Comment by ijpiantanida** [comment]
Compressing files on the fly is CPU consuming for the web server.
By pre-compressing assets, you serve them as any other static file.

**Comment by zzzgit** [comment]
Will it rise the configuration of web server?What should I do after the generation of compacted files?

**Comment by ijpiantanida** [comment]
This doesn't touch the web server. It just creates the compressed assets. You should then put them with all the other static assets you have (along side the uncompressed assets).

You should also make sure that your web server is able to deliver both compressed and uncompressed assets based on the Accept header.

**Comment by zzzgit** [comment]
Okay thanks
