### ISSUE TITLE
why i have double output file .gzip and original file !!!

### ISSUE THREAD

**Issue by AhmedHadjTaieb** [webpack-contrib/compression-webpack-plugin#46]
Angular-CLI 1.0.0 RC0
Webpack 2.2.1

i use webpack CompressionPlugin and when i run npm build i found double file with the same name in dist folder, it's correct ???
my code for output in webpack.conf.js :
"output": {
    "path": path.join(process.cwd(), "dist"),
    "filename": "[name].bundle.js",
    "chunkFilename": "[id].chunk.js"
  },

![2017-03-02](https://cloud.githubusercontent.com/assets/22799068/23504113/7691532e-ff3e-11e6-8e26-57678514b6b5.jpg)

**Comment by leefsmp** [comment]
same ... guidance is appreciated, your readme is rather minimalistic

**Comment by TomDeBacker** [comment]
Original file and compressed file..

**Comment by michael-ciniawsky** [comment]
@AhmedHadjTaieb  @leefsmp  @TomDeBacker Discussion moved to #44
