### ISSUE TITLE
can not work with png and html

### ISSUE THREAD

**Issue by changfuguo** [webpack-contrib/compression-webpack-plugin#47]
config as below:

```
new CompressionWebpackPlugin({
                asset: '[path].gz[query]',
                algorithm: 'gzip',
                test: new RegExp(
                '\\.(' +
                    ['png', 'gif','html'].join('|') +
                ')$'
                ),
                threshold: 1024,
                minRatio: 0
        })
```
and i am sure the size of file greater than 1024
output list as below:

![](https://raw.githubusercontent.com/changfuguo/share/master/images/compression_webpacl_plugin_issue/123.png)

**Comment by michael-ciniawsky** [comment]
@changfuguo Do you load the `png/html` via webpack ?

**Comment by michael-ciniawsky** [comment]
@changfuguo If you still have problems feel free to reopen or open a new issue :)

**Comment by nylin93** [comment]
@changfuguo Not sure if this has been cleared up but for future reference, gzip compression of images is not recommended and can actually result in a [**larger** file size.](https://developer.yahoo.com/performance/rules.html).
