### ISSUE TITLE
node-zopfli not found eventhough it is installed

### ISSUE THREAD

**Issue by Eightyplus** [webpack-contrib/compression-webpack-plugin#48]
```
/usr/src/app/node_modules/compression-webpack-plugin/index.js:20
				throw new Error("node-zopfli not found");
				^

Error: node-zopfli not found
    at new CompressionPlugin (/usr/src/app/node_modules/compression-webpack-plugin/index.js:20:11)
    at getPluginsConfig (/usr/src/app/webpack.config.js:262:5)
    at Object.<anonymous> (/usr/src/app/webpack.config.js:335:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)```
```
So the require in `compression-webpack-plugin/index.js` fails...

```
yarn list | grep node-zopfli
warning digitransit-ui@0.0.1: License should be a valid SPDX license expression
│  ├─ node-zopfli@^2.0.0
├─ node-zopfli@2.0.2
```

**Comment by Eightyplus** [comment]
I't works when install `node-zopfli@2.0.0`, please use specific version!

**Comment by michael-ciniawsky** [comment]
@Eightyplus Curious, why the version must be specific ? 😛

**Comment by Eightyplus** [comment]
You tell me, you created the loose dependency.

**Comment by michael-ciniawsky** [comment]
kk I see now 😛 , I'm not the maintainer here, I will check why it is there in the first place and if it can be safetly removed, mom.

**Comment by Eightyplus** [comment]
We are struggeling with loose dependencies and migrating toward yarn to avoid this problem. But now and then it breaks because we haven't locked down all dependencies :)

**Comment by michael-ciniawsky** [comment]
Setting it and the current range maybe also wrong :)

**Comment by Eightyplus** [comment]
I'm still trying to locate the exact problem, printing `console.log(err)` before the error is thrown I get the following. It could indicate problems with another dependency, I'll keep you updated.

```
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /usr/src/app/node_modules/node-zopfli/lib/binding/node-v51-linux-x64/zopfli.node)
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/node_modules/node-zopfli/lib/zopfli.js:7:14)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/src/app/node_modules/babel-register/lib/node.js:152:7)
```

**Comment by Eightyplus** [comment]
What version of node/npm is required?

**Comment by michael-ciniawsky** [comment]
> What version of node/npm is required?

@Eightyplus webpack 1 + plugin should be fine with node`>= 0.12.x` && npm `>=2.x`, webpack 2 requires node `>= 4`

> /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /usr/src/app/node_modules/node-zopfli/lib/binding/node-v51-linux-x64/zopfli.node)

This is a node native modules (C/C++) issue in `node-zopfli`  the glibc on your system may mismatch with the one required by `node-zopfli`. Why and if this an issue because of the node version in use etc., I'm no real help here, since C/C++ isn't my daily bread :D

**Comment by Eightyplus** [comment]
Hi, it turn out it is a build vs. runtime environment issue. Sorry about that.

**Comment by EvgenyKravchenko** [comment]
@Eightyplus Hey, I've got the same issue. 
```
Error: Cannot find module '/usr/src/app/node_modules/node-zopfli/lib/binding/node-v51-linux-x64/zopfli.node'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
```
How did you solve this? Thanks

**Comment by Eightyplus** [comment]
Well, the build/runtime environment was different, so the packages has to be rebuild as suggested 
`rm -rf node_modules && npm install`

**Comment by EvgenyKravchenko** [comment]
Hmm, I'm trying to run it inside fresh docker container and getting these error. Anyway, thank you

**Comment by EvgenyKravchenko** [comment]
It's strange, but locally with NODE_ENV=production everything is working. So something is missing in docker container

**Comment by Eightyplus** [comment]
Maybe your production env is different the other. I would check my `webpack.config.js` then.

**Comment by d3viant0ne** [comment]
@Eightyplus - For reference, zopfli is being split out into it's own lib in the upcoming Major version of compression-webpack-plugin.

**Comment by Eightyplus** [comment]
@d3viant0ne thanks for letting me know!

**Comment by d3viant0ne** [comment]
FYI the compression-webpack-plugin@1.0.0-beta.1 release officially remove the lose dependency. More information can be found in the `changelog.md`
