### ISSUE TITLE
Chunk name

### ISSUE THREAD

**Issue by audiolion** [webpack-contrib/compression-webpack-plugin#49]
Hello,

Is there a way to attach a chunk name to this output? Other plugins I use work on the chunks that were output and this plugin doesn't attach any chunk name.

This may not be possible (e.g. this plugin is taking the chunks and compressing them and outputting them), but it would be nice if that were the case that it would delete the old files (this function is already there) and the new files would have the same chunk name as the uncompressed version

**Comment by michael-ciniawsky** [comment]
@audiolion Could you provide a small example (code) for that please 😛

**Comment by sibelius** [comment]
you can use `[chunkhash]` in your bundle names

this package will only add `.gz` to it

example

```jsx
new CompressionPlugin({
      asset: '[path].gz[query]',
      algorithm: 'gzip',
      test: /\.(js|html)$/,
      threshold: 10240,
      minRatio: 0.8,
    }),
```

**Comment by michael-ciniawsky** [comment]
@audiolion See @sibelius post
@sibelius Thx 😛

**Comment by xitter** [comment]
Added more descriptive issue: https://github.com/webpack-contrib/compression-webpack-plugin/issues/185
