### ISSUE TITLE
deleteOriginalAssets not working?

### ISSUE THREAD

**Issue by myknbani** [webpack-contrib/compression-webpack-plugin#50]
I stll have my original vendor.js bundle alongside vendor.js.gz.  Curious if this works with multiple entry points.

```js
new CompressionPlugin({
        test: /\.(js|css|html)$/,
        threshold: 10240,
        deleteOriginalAssets: true,
}),
```

**Comment by mastilver** [comment]
If you look at the code, it's not actually deleting the file, just removing it from the webpack output

https://github.com/webpack-contrib/compression-webpack-plugin/blob/master/index.js#L84-L86

**Comment by michael-ciniawsky** [comment]
@myknbani @mastilver Tbh, I need to investigate, why this is the current behaviour and if it's simply a bug. Any position upon that, please express them 😛

**Comment by mastilver** [comment]
I guess it could be confusing, but to me it doesn't matter as long as it's removed from the `assets`

**Comment by Milewski** [comment]
I guess his build dir might not be cleared before each build and the js left were result of the previous one...

**Comment by myknbani** [comment]
@Milewski  My build dir is cleared.  I'll try this without multiple entry points

```
$ ls -lh public
total 0
$ yarn build:frontend:prod              
yarn build:frontend:prod v0.22.0
$ rm -rfv public/ && NODE_ENV=production webpack --config webpack-prod.config.js --progress 
removed directory 'public/'

... removed output

$ tree public/
public/
├── images
│   └── cpu-logo.png
├── index.html
└── js
    ├── core.9ac02e1601154e1fac43.js
    ├── manifest.5b61900d77f1b5d85f2c.js
    ├── vendor.ef4fc9cace66a6feb492.js
    └── vendor.ef4fc9cace66a6feb492.js.gz

2 directories, 6 files
$ 
```

**Comment by myknbani** [comment]
Still no luck, I tried removing plugins except Uglify and Compression... with only 1 entry point.
Original asset still there.

```
public/
├── images
│   └── cpu-logo.png
└── js
    ├── main.374023ff72b5b0e88167.js
    └── main.374023ff72b5b0e88167.js.gz
```

**Comment by michael-ciniawsky** [comment]
@myknbani Yep currently this is the expected behaviour according to the code, but the question is why (e.g as fallback) or because the code is incorrect and it can be removed?

**Comment by myknbani** [comment]
Sorry, I'm not really familiar with Webpack internals.   But I saw this on SO, one guy made a SupressChunkPlugin, and `delete` was also used.

```
SuppressEntryChunksPlugin.prototype.apply = function(compiler) {
  var options = this.options;

  // just before webpack is about to emit the chunks,
  // strip out primary file assets (but not additional assets)
  // for entry chunks we've been asked to suppress
  compiler.plugin('emit', function(compilation, callback) {
    compilation.chunks.forEach(function(chunk) {
      if (options.skip.indexOf(chunk.name) >= 0) {
        chunk.files.forEach(function(file) {
          delete compilation.assets[file];
        });
      }
    });
    callback();
  });
};
```

**Comment by myknbani** [comment]
Ugh!  I was about to experiment with doing some `console.log`s inside node_modules, and guess what?  I have an old version.  I treated the Gthub readme as the official docs.

This is a recent addition and not yet released on NPM!  I can see that `deleteOriginalAssets` is not documented on NPM.

It works with the github version, so sorry for the trouble.  

```
└── js
    ├── core.9ac02e1601154e1fac43.js
    ├── manifest.5b61900d77f1b5d85f2c.js
    └── vendor.ef4fc9cace66a6feb492.js.gz
```

**Comment by d3viant0ne** [comment]
@myknbani - I'll have this out on NPM shortly.
