### ISSUE TITLE
Split out node-zopfli

### ISSUE THREAD

**Issue by d3viant0ne** [webpack-contrib/compression-webpack-plugin#56]
- Support from  `node-zopfli` will be dropped from `compression-webpack-plugin` in the next Major release. 

`zopfli-webpack-plugin` will be published with an identical API less the optional dependency.

Relates to #54

**Comment by ivasilov-h4** [comment]
What's the timeline on this change? Can it be done any sooner?

**Comment by d3viant0ne** [comment]
@ivasilov-h4 - It will be done this week, limited about of project bandwidth for the org-maintainers once you subtract managing issues / pull requests.

**Comment by ciscoo** [comment]
This split out will remedy https://github.com/pierreinglebert/node-zopfli/issues/87.
Seems the project maintainer seems to be absent.

**Comment by d3viant0ne** [comment]
FYI - https://github.com/webpack-contrib/zopfli-webpack-plugin
