### ISSUE TITLE
Using Compression plugin alongside 'html-webpack-plugin'

### ISSUE THREAD

**Issue by retwedt** [webpack-contrib/compression-webpack-plugin#57]
Is it possible to make the Html Webpack plugin insert a link to the .gz build file instead of the normal .js build file?

Is this even the right place to ask this question??

Thanks for your help, and thanks for your work on a great plugin!

**Comment by retwedt** [comment]
Apparently this is a duplicate of #45

**Comment by farhan687** [comment]
No update even after a month?

**Comment by lucasvinals** [comment]
Hi guys, I've just wrote a simple plugin to connect both plugins.
It just listen for HtmlWebpackPlugin to complete it's build and then change the extensions to files that you specify.

You can download with `yarn add change-extension-plugin` or `npm install change-extension-plugin --save`. Cheers! :smiley:

**Comment by retwedt** [comment]
@lucasvinals Awesome I will check it out!

**Comment by marcoturi** [comment]
@d3viant0ne Now that the PR is merged and published, can you show how to use this plugin with html-webpack-plugin? Thank you

**Comment by urikphytech** [comment]
Hi, I also can't find any documentation on how to make this work with html-webpack-plugin (i.e. have html-webpack-plugin write the path with the correct file extension).

Can anyone here point me in the right direction? I'd be happy to document it.
Thanks!

**Comment by nerdmax** [comment]
Just in case some one else find this issue later.

If you are using `html-webpack-plugin` along side `compression-webpack-plugin` and you want the `html-webpack-plugin` to reference the .gz file automatically.

You can try this plugin: [html-webpack-change-assets-extension-plugin](https://github.com/nerdmax/html-webpack-change-assets-extension-plugin).

Eg:
```javascript
plugins: [
  new HtmlWebpackPlugin({
    jsExtension: ".gz"
  }),
  new CompressionPlugin(), // compression plugin will generate the xxx.js.gz file
  new HtmlWebpackChangeAssetsExtensionPlugin()
];
```
