### ISSUE TITLE
Set content-econding: gzip header in gzipped files

### ISSUE THREAD

**Issue by Danjavia** [webpack-contrib/compression-webpack-plugin#58]
Ho to add a new meta content-encoding: gzip to gzipped files?

**Comment by enzolutions** [comment]
Hi, guys great job BTW.

I have the same question, how I could include gzip files in my HTML or must be normal and I have to include some extra configuration in muy server Apache, Nginx, etc?

**Comment by michael-ciniawsky** [comment]
Can someone please explain with some code what's the goal here, normally `content-encoding` etc. is configured by the webserver

**Comment by djbingham** [comment]
I think I've hit the same issue as the OP (or very similar).

My goal is to have Nginx serve either a gzipped or uncompressed file for each request, depending on whether the uncompressed size exceeds a threshold. To achieve this, I've setup the Webpack Compression Plugin with a threshold for file size (as per the README example) and configured Nginx to check for a ".gz" extended version of each requested file.

**WebPack configuration:**

```
new CompressionPlugin({
	asset: "[path].gz[query]",
	algorithm: "gzip",
	test: /\.js$|\.css$|\.html$/,
	threshold: 10240,
	minRatio: 0.8
})
```

**Nginx configuration:**
```
location / {
	root /srv/app;
	try_files $uri.gz $uri =404;
}
```

**Expected result:**
Nginx serves gzipped JS files with `Content-Type: application/javascript` and `Content-Encoding: gzip`.

**Actual result:**
Browser received gzipped files with `Content-Type: application/x-gzip` and no `Content-Encoding` value.

I'm new to compressing assets for the web and don't know whether it's possible to set file meta-data that Nginx (or other web servers) will parse into Content-Type and Content-Encoding values, but if it is I think it should be done by this plugin. If not, I'll just have to use a smarter Nginx configuration.

**Comment by willin** [comment]
mark

**Comment by michael-ciniawsky** [comment]
This is a config issue with the webserver in use and unrelated to this plugin as it simply compresses the assets for further usage. Please consider the docs of your webserver

**Comment by rupamkhaitan** [comment]
You dont need to define in the location
location / {
	gzip_static on;
	rewrite ^/?$ /index.html break;
	root /srv/app;
}

In the main /etc/nginx/nginx.conf

just enable inside 

http{

#enable compression of data
  gzip on;

}

And see it will compress the files and send
