### ISSUE TITLE
compression-webpack-plugin and ZopfliWebpackPlugin , what different? what better?

### ISSUE THREAD

**Issue by anlexN** [webpack-contrib/compression-webpack-plugin#59]
compression-webpack-plugin and ZopfliWebpackPlugin , what different? what better?

**Comment by d3viant0ne** [comment]
@anlexN - I am splitting out the different compression libs into separate loaders.

`gzip` is the most commonly used, the faster of the two but doesn't compress quite as much ( ~5% dependent on what you are compressing ).

`Zopfli` is pretty much the exact opposite but does come with a few system level requirements that gzip does not ( python for one ).

The change has little to do with what is better. Currently `compression-webpack-plugin` has a loose dependency on `Zopfli` which can cause dependency issues in continuous integration workflows.

For the next major release of `compression-webpack-plugin` the `zopfli` option and it's loose dependency will be dropped and be published in conjunction with the initial release of `zopfli-webpack-plugin`.

**Comment by anlexN** [comment]
these plugn will be changed to loader? when is the next major release? will you drop zopfli-webpack-plugin?

**Comment by d3viant0ne** [comment]
zopfli-webpack-plugin hasn't been published yet. That needs to go out first, then a `1.0.0-beta` version of `compression-webpack-plugin` needs to be published which includes the `webpack-defaults` updates and drops the zopfli option.

**Comment by anlexN** [comment]
@d3viantOne, you are good man.
from webpack/hot-node-example repository:
i have a problem when i target: 'node" in webpack , want to use in the browser. i also use node-libs-browser , but see below!
![require warning](https://cloud.githubusercontent.com/assets/8686739/26272759/5477ff56-3d53-11e7-9d24-b8b5d8aa52f9.PNG)
![require](https://cloud.githubusercontent.com/assets/8686739/26272760/555a2778-3d53-11e7-8b93-5a11eee90054.PNG)

**Comment by michael-ciniawsky** [comment]
Closing as the initial question was answered. You won't need to compress (gzip) your files when running with `node` as the target as compression is only useful to minimize file size for **sending data** over the network
