### ISSUE TITLE
how to use the compressed gz file

### ISSUE THREAD

**Issue by guguji5** [webpack-contrib/compression-webpack-plugin#69]
I run the vue-cli,and build my project.the vendor builded is too large.so i gzip it and turn to several gz files.but i don't know how to use it.its size seem to suitable.

**Comment by michael-ciniawsky** [comment]
If you get `.gz` files the job of this plugin is done 😛 , you need to configure your webserver to serve gzip resources (Encoding, HTTP Headers etc), depending which server you use this info can be found in the docs as it is a standard configuration task.

**Comment by BorjaRafols** [comment]
That is not problem @michael-ciniawsky.

However in my case I'm upoading .gz file to cloudfront, so I can not add a middleware on my webserver, instead I need wepack to request the .gz url of the assets instead of the normal one.
