### ISSUE TITLE
Not minifying?

### ISSUE THREAD

**Issue by kenjim83** [webpack-contrib/compression-webpack-plugin#7]
Hi Tobias!

I'm probably doing something wrong but I can't get the CompressionPlugin to generate the final gzipped .gz file during production build.

Here's my webpack.config file:

var webpack = require('webpack');
var baseConfig = require('./webpack/base-config');
var configurationCreator = require('webpack-configuration');
var CompressionPlugin = require('compression-webpack-plugin');
var path = require('path');

module.exports = configurationCreator(baseConfig, {
  commonsChunk: false,
  longTermCaching: false,
  extractCSS: true,
  path: 'server/cloud/assets/',
  publicPath: "server/cloud/assets/",
  versionMap: path.join(__dirname, 'server/assets.json'),
  plugins: [
    new webpack.optimize.UglifyJsPlugin(),
    new webpack.optimize.DedupePlugin(),
    new CompressionPlugin({
        asset: "{file}.gz",
        algorithm: "gzip",
        regExp: /.js$/,
        threshold: 0,
        minRatio: 0.8
    })
  ]
});

This does, however, produce the minified .js in 'server/cloud/assets/'. Any help would be greatly appreciated!

**Comment by Peekab0o** [comment]
Have you found an error?

**Comment by erwingaitano** [comment]
I took me a while to notice that my gz files weren't being generated until a few days ago. Previously in the plugin config, the asset key was: `"{file}.gz"` but I noticed that they changed it to `"[file].gz"`.

**Comment by palmerj3** [comment]
@erwingaitano hello! Has this been resolved?

**Comment by erwingaitano** [comment]
Yes, this was resolved at least in my case. I think it was due to breaking changes introduced in a later version at that time, where `{file}.gz` was replaced with `[file].gz`, making already configs using `{file}.gz` to crash.
