### ISSUE TITLE
.gz file names not updated in index.html

### ISSUE THREAD

**Issue by akashbiz** [webpack-contrib/compression-webpack-plugin#75]
Hello, I am using this plugin to gzip my bundle and chunk js so that my application should load faster. I followed integration steps and build generates .gz files too but those .gz file names are not updated in index.html Have anyone face this issue?

Also it adds scripts two times in index.html
1. In Head: as link and type preload
2. In Body: as script and type test/javascript
can you explain me why it is used two times?

my index.html file still looks like:

```
<!doctype html>
<html lang=en>

<head>
<title>Gzip compression</title>
<base href="/">
<link rel="stylesheet" href="assets/css/style.css">  
<link rel="preload" href="polyfills.bundle.js" as="script"/><link rel="preload" href="main.bundle.js" as="script"/>
</head>

<body>
<app>Loading...</app>
<script type="text/javascript" src="polyfills.bundle.js"></script><script type="text/javascript" src="main.bundle.js" async></script
</body>

</html>
```

**Comment by michael-ciniawsky** [comment]
If you use `html-webpack-plugin`, it's currentlx a bug/known issue (#71), otherwise `compression-webpack-plugin` doesn't alter anything by itself here

**Comment by akashbiz** [comment]
Yes, I have gone through that issue, but even after changing in index.html manually, in browser its loading entire content within gz file.
My main.bundle.js was 1.1 MB initially without use of compression plugin, after using compression it became 446KB and saved on my local. When I deploy this build on aws s3, it shows 1.1MB transferred for  this gzip file. Also, its not showing the content-encoding as gzip in dev tools. 

Any idea what am I doing wrong?

**Comment by akashbiz** [comment]
Also, If I update .gz extension manually to bundle files still in browser its not showing content-encoding: gzip, Content-Length is also not visible. So is there any other setting required to add these content-encoding as gzip so that browser can download only 286KB and unzip them in browser?

**Comment by michael-ciniawsky** [comment]
This needs to be configured in your 'webserver' config separately (send with the correct `content-encoding` header). No idea how to enable it for AWS sry :)

**Comment by OlzhasAlexandrov** [comment]
@akashbiz 
You need to set an appropriate header for the objects that are gzip compressed, either using the [CLI](http://docs.aws.amazon.com/cli/latest/reference/s3/index.html) or manually adjusting each object in the web console. Example using CLI:
`$ aws s3 sync . s3://bucketName --content-encoding gzip --metadata-directive REPLACE`

**Comment by michael-ciniawsky** [comment]
@OlzhasAlexandrov Thx 👍

**Comment by nerdmax** [comment]
Just in case some one else find this issue later.

If you are using `html-webpack-plugin` along side `compression-webpack-plugin` and you want the `html-webpack-plugin` to reference the .gz file automatically.

You can try this plugin: [html-webpack-change-assets-extension-plugin](https://github.com/nerdmax/html-webpack-change-assets-extension-plugin).

Eg:
```javascript
plugins: [
  new HtmlWebpackPlugin({
    jsExtension: ".gz"
  }),
  new CompressionPlugin(), // compression plugin will generate the xxx.js.gz file
  new HtmlWebpackChangeAssetsExtensionPlugin()
];
```

**Comment by rcklmk** [comment]
@o-alexandrov 
Hi, I'm glad that I found your comment, it helped me solve the problem of serving gzipped static assets directly from S3 (especially webpack chunks).

> AWS S3 uncompresses the objects by itself before responding to the request, if the client's browser doesn't support GZIP.
With regards to on-the-fly gzip decompression, I was wondering if you could provide any reference to the page that documents this behavior or some way to test it - I tried googling, but the ones I found were talking about CloudFront's automatic compression feature instead. Thanks

**Comment by rcklmk** [comment]
@o-alexandrov 
Hi, I'm glad that I found your comment, it helped me solve the problem of serving gzipped static assets directly from S3 (especially webpack chunks).

> AWS S3 uncompresses the objects by itself before responding to the request, if the client's browser doesn't support GZIP.

With regards to on-the-fly gzip decompression, I was wondering if you could provide any reference to the page that documents this behavior or some way to test it - I tried googling, but the ones I found were talking about CloudFront's automatic compression feature instead. Thanks
