### ISSUE TITLE
Update documentation about zopfli

### ISSUE THREAD

**Issue by tkrotoff** [webpack-contrib/compression-webpack-plugin#76]
CompressionPlugin documentation says you can specify `algorithm: 'zopfli'`, I believe this is not true anymore because of this commit that removed zopfli: https://github.com/webpack-contrib/compression-webpack-plugin/commit/328048a93bcb0b18945810144b180a161e271291#diff-1fdf421c05c1140f6d71444ea2b27638L17 (see also #65)
Same for webpack documentation: https://webpack.js.org/plugins/compression-webpack-plugin/

If you try to specify `algorithm: 'zopfli'` it crashes with `Error: Algorithm not found in zlib`

If CompressionPlugin supports only gzip, then it should be renamed to gzip-webpack-plugin/GzipPlugin.

See also #59

**Comment by davidbucka** [comment]
same her

**Comment by michael-ciniawsky** [comment]
This should be updated on the docs page && README https://webpack.js.org/plugins/compression-webpack-plugin/ (#72) now. Feel free to reopen if still regressions :)

**Comment by pablote** [comment]
I just run into this issue, so is zopfli not supported anymore? or is there another way to use it?

**Comment by michael-ciniawsky** [comment]
https://github.com/webpack-contrib/zopfli-webpack-plugin
