### ISSUE TITLE
[Bug] Dynamic (computed) `import()` chunks aren't compressed

### ISSUE THREAD

**Issue by shye0000** [webpack-contrib/compression-webpack-plugin#79]
Hi I have some translation js files which imported dynamically like this in the code: 

![selection_243](https://user-images.githubusercontent.com/6414361/32096339-7590b9ae-bb06-11e7-9011-1a892f46b08a.png)

And here is the output of my webpack build with compression-webpack-plugin:

![selection_244](https://user-images.githubusercontent.com/6414361/32096463-cf4cde50-bb06-11e7-9b73-099aea97a9ba.png)

As you can see in the screen shot, only the first with index "0" is compressed but not the second one.

Any idea for this issue? Thanks a lot in advance for your help.

**Comment by jamesfiltness** [comment]
+1 - I'm experiencing the same issue: ![compression](https://i.imgur.com/qj0be4P.png)

**Comment by michael-ciniawsky** [comment]
@jamesfiltness Are you also using computed values in the `import()` path to generate multiple chunks ?

Could someone make a small repo for reproduction please ?

**Comment by jamesfiltness** [comment]
@michael-ciniawsky Sure I have a repo that demonstrates the issue. The dynamic `import()` that doesn't get compressed is imported here: https://github.com/jamesfiltness/webpack-2-code-splitting/blob/master/src/universal/app.js#L14

**Comment by evilebottnawi** [comment]
@jamesfiltness @shye0000 don't reproducible, seems you have default `minRatio`, just try increase value (use `minRatio: Number.MAX_SAFE_INTEGER` for compress all assets)

**Comment by michael-ciniawsky** [comment]
Feel free to reopen if still regressions

**Comment by fercho0** [comment]
### compress all files
```  
 new CompressionPlugin({
            asset     : '[path].gz[query]',
            algorithm : 'gzip',
            test      : /\.js$|\.css$|\.eot?.+$|\.ttf?.+$|\.woff?.+$|\.svg?.+$/,
            minRatio: Number.MAX_SAFE_INTEGER, // Compress everything
            //minRatio  : 0.5,
            cache     : true,
            threshold: 0,
            threshold: 10240,
            deleteOriginalAssets : false
        })```


![example](https://user-images.githubusercontent.com/20364582/41213126-cab2c4cc-6d08-11e8-8bd4-8104b830ce27.png)

**Comment by guanzo** [comment]
None of these options are working for me. Dynamic imports aren't being compressed.
