### ISSUE TITLE
net::ERR_CONTENT_DECODING_FAILED after updating from v1.0.1 to v1.1.3

### ISSUE THREAD

**Issue by nekman** [webpack-contrib/compression-webpack-plugin#93]
Serving files from AWS S3 via Cloudfront. 
Everything works as expected with version 1.0.1 with the following configuration:

```javascript
new CompressionPlugin({
    asset: '[path]',
    algorithm: 'gzip',
    test: /\.js$|\.css$|\.html$/,
    threshold: 10240,
    minRatio: 0
  })
```

When I run the same configuration with the latest version (1.1.3) I got a blank page saying: "net::ERR_CONTENT_DECODING_FAILED"

Using webpack version: 3.10.0

**Comment by evilebottnawi** [comment]
@nekman can you create minimum reproducible test repo?

**Comment by nekman** [comment]
Late reply.

Sorry @evilebottnawi , but I can't do that (right now).
I updated to v1.1.6 but the problems still occurs. 

It looks like I don't get a gzipped file, when running v1.1.6. I can open/view the bundle in VS Code after compression:
![1 1 6](https://user-images.githubusercontent.com/568019/35982312-c9dd621a-0cef-11e8-8fe9-786bf4e4201e.png)

But with v1.0.1 I get:
![1 0 1](https://user-images.githubusercontent.com/568019/35982337-d3aea768-0cef-11e8-9018-57c23e4c7411.png)

Which looks correctly compressed and works. 

Using OSX 10.13.2 and Node v8.9.0

**Comment by evilebottnawi** [comment]
@nekman very strange, can you provide what files you gzip (add `console.log(file)` here https://github.com/webpack-contrib/compression-webpack-plugin/blob/master/src/index.js#L77) and put here file what occurs error

**Comment by nekman** [comment]
Both versions logs:
```
>> FILE: main.702e5cc1fb2c4ad0fe8d.js
>> FILE: index.html

```
<img width="760" alt="log" src="https://user-images.githubusercontent.com/568019/35994268-30a7828a-0d10-11e8-8667-318aa16b0e51.png">

I think this is a config error. Changed the config above to:

```javascript
  WebpackConfig.plugins.push(new CompressionPlugin({
    asset: '[path]',
    algorithm: 'gzip',
    test: /\.js$|\.css$|\.html$/,
    // threshold: 10240,
    // minRatio: 0
  }));
```
And this compressed the file with version 1.1.6. However, it did not work after deployment. This is how it looked in the browser:

<img width="228" alt="strange-encoding" src="https://user-images.githubusercontent.com/568019/35994399-95ba1b56-0d10-11e8-975d-265a8d71f3eb.png">

**Comment by evilebottnawi** [comment]
@nekman seems problem with html right?

**Comment by nekman** [comment]
It looks like that. Will try to remove html by only using: `test: /\.js$|\.css$/, `

**Comment by nekman** [comment]
@evilebottnawi the following configuration worked successfully on v1.1.6:

```javascript
  WebpackConfig.plugins.push(new CompressionPlugin({
    asset: '[path]',
    algorithm: 'gzip',
    test: /\.js$|\.css$/,
    // threshold: 10240,
    // minRatio: 0
  }));
```

Thanks!

**Comment by evilebottnawi** [comment]
@nekman let's investigate why html was broken :+1:

**Comment by evilebottnawi** [comment]
@nekman do you have `index.html.gz` ? Can you put this here?

**Comment by nekman** [comment]
Wait a moment, I don't think html is broken. I think its my deployment script that was broken.
When uploading gzipped files to AWS S3, you need to tell S3 what files that are gzipped.

This is what I do:
```
# upload everything except gzipped "main" bundle
aws s3 cp dist/ s3://bucket-dev/ --exclude "main*.js" --recursive --region eu-west-1

# upload only the "main" js-bundle with gzip headers
aws s3 cp dist/ s3://bucket-dev/ --exclude "*" --include "main*.js"  --recursive --content-encoding 'gzip' --region eu-west-1
```
I must do the same with the html file as well. Will try to do that!

**Comment by michael-ciniawsky** [comment]
The `Content-Encoding` header just be configured to serve `.gz` files explicitly on most hosting services, so browsers are able to decode it
