### ISSUE TITLE
Latest release is empty

### ISSUE THREAD

**Issue by appellation** [webpack-contrib/compression-webpack-plugin#96]
I just installed v1.1.4 from npm, but got an error `cannot find module 'compression-webpack-plugin'`.  After some investigation, I found that the `node_modules` folder for the plugin was empty except for some root files.  This seems to be an issue with the module not being properly built before release?

![image](https://user-images.githubusercontent.com/8494131/35527238-eb477f08-04de-11e8-87ce-63eeed576660.png)

- Node version: 8.9.0
- npm version: 5.6.0
- OS: Windows 10 Pro

**Comment by kflorence** [comment]
![ship it](http://cultofthepartyparrot.com/parrots/shipitparrot.gif)

**Comment by michael-ciniawsky** [comment]
Yeah there is something wrong. Investigating why...

**Comment by madasu** [comment]
@michael-ciniawsky, this breaks our build pipe line... Fix is much appreciated...

**Comment by madasu** [comment]
@michael-ciniawsky, "compression-webpack-plugin": "1.1.3" throws error:
npm ERR! enoent ENOENT: Cannot cd into '\node_modules\.staging\compression-webpack-plugin-ddc68184'
npm ERR! enoent This is related to npm not being able to find a file.

**Comment by chabanov** [comment]
Cannot find module 'compression-webpack-plugin'

**Comment by chabanov** [comment]
compression-webpack-plugin@^1.1.3:
  version "1.1.5"
  resolved "https://registry.yarnpkg.com/compression-webpack-plugin/-/compression-webpack-plugin-1.1.5.tgz#b680e20a5abb20fe7fa12c6cb5e597cd4ba3a995"

**Comment by yoojinl** [comment]
I see that new version (v1.1.5) was released after this, but it seems like it's still causing the same issue.

**Comment by michael-ciniawsky** [comment]
Fix coming in a few minutes

**Comment by michael-ciniawsky** [comment]
[`v1.1.6`](https://github.com/webpack-contrib/compression-webpack-plugin/releases/tag/v1.1.6)

Sry guys it was clearly my mistake during release 😅

**Comment by yoojinl** [comment]
Thank you! 👍

**Comment by teeeg** [comment]
Thanks!

**Comment by kflorence** [comment]
Appreciate the quick turnaround time!
