### ISSUE TITLE
minRatio option documentation misleading

### ISSUE THREAD

**Issue by RinkAttendant6** [webpack-contrib/compression-webpack-plugin#99]
My initial problem was that my CSS files were only compressed using Brotli but not Gzip. After trying different things for a while, I noticed this option:

> `minRatio` `{Number}` Only assets that compress better than this ratio are processed

I would assume setting it to `0` would tell the plugin to compress no matter what. From Wikipedia:
> Data compression ratio is defined as the ratio between the uncompressed size and compressed size:
> 
> Compression Ratio = Uncompressed Size / Compressed Size
>
> Thus a representation that compresses a 10 MB file to 2 MB has a compression ratio of 10/2 = 5, often notated as an explicit ratio, 5:1 (read "five" to "one"), or as an implicit ratio, 5/1.

https://en.wikipedia.org/wiki/Data_compression_ratio

For example, an uncompressed CSS file of 193 KiB compressed to 170 KiB means a compression ratio of ~1.135, which is greater than 0. In fact, anything that decreases in size would be > 1.

Anyways, everything compressed after I set the value to `Infinity`, so I'm not really sure how this number is being used in the calculations.

**Comment by evilebottnawi** [comment]
@RinkAttendant6 PR welcome

**Comment by RinkAttendant6** [comment]
@evilebottnawi I briefly looked at the code and it looks like the value is being compared with the *inverse* of the compression ratio (compressed size / uncompressed size). So if I want to only compress if the ratio is greater than 5x, the value I'm supposed to use is 1/5 or 0.2.

I'm not exactly sure how to describe that.

**Comment by evilebottnawi** [comment]
Done in https://github.com/webpack-contrib/compression-webpack-plugin/releases/tag/v2.0.0

Feel free to feedback.
